#!/bin/sh
LIBDIR=/opt/WebSphere/AppServer/lib
CLASSPATH=$LIBDIR/j2ee.jar:$LIBDIR/ns.jar:$CLASSPATH
export CLASSPATH
if [ $# -lt 1 ]
then
	JARFILE=TopCoder
else
	JARFILE=$1
fi
if [ ! -d classes ]
then
	mkdir classes
fi
if [ ! -d classes/META-INF ]
then
	mkdir classes/META-INF
fi
cp *.xml *.xmi classes/META-INF
cd classes
echo "Compiling sources..."
javac -d . ../com/topcoder/web/render/ejb/*.java
echo "Creating $JARFILE.jar"
jar cf ../$JARFILE.jar .
