<HTML>
<HEAD>
	<TITLE>::TopCoder High School::</TITLE>
    <META NAME="description" CONTENT="TopCoder is a programming tournament site. All members who compete attain a rating that provides a metric for coding competence and potential. These ratings, coupled with tournament performance, can lead to monetary rewards and employment opportunities."/>
    <META NAME="keywords" CONTENT="Computer Jobs, Programming, Programming Jobs, Programming Contest, Programming Competition, Online Games, Coding, Information Technology Jobs, Java, C++"/>
<jsp:include page="../includes/css.jsp" />
</HEAD>
<BODY BGCOLOR="#001934" TOPMARGIN="0" MARGINHEIGHT="0" LEFTMARGIN="0" MARGINWIDTH="0">
<jsp:include page="../includes/top.jsp" />
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000000" WIDTH="100%">
<TR><TD>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#FFFFFF" WIDTH="100%">
    <TR VALIGN="top">
		<TD WIDTH="170" BGCOLOR="#001934">
        <jsp:include page="../includes/left_nav.jsp" />
        <jsp:include page="../includes/left_calendar.jsp" />
        </TD>
        <TD WIDTH="1" BGCOLOR="#C5C5C9" VALIGN="top"><IMG SRC="/i/hs/frame_1pix_bg_lg_top_left.gif" WIDTH="1" HEIGHT="3" ALT="" BORDER="0"></TD>
        <TD WIDTH="1" BGCOLOR="#000000" VALIGN="top"><IMG SRC="/i/hs/frame_1pix_bg_lg_top_left.gif" WIDTH="1" HEIGHT="3" ALT="" BORDER="0"></TD>
        <TD VALIGN="top" BACKGROUND="/i/hs/bluegradiant_bg.gif" BGCOLOR="#FFFFFF">
            <TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0" WIDTH="100%">
    <TR>
        <TD>
            <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="" WIDTH="100%">
             <TR><TD ALIGN="left" HEIGHT="44" WIDTH="348"><IMG SRC="/i/hs/headinginside_faq.gif" WIDTH="348" HEIGHT="44" BORDER="0"></TD>
             <TD BACKGROUND="/i/hs/headinginside_1pix_bg.gif" ALIGN="left" HEIGHT="44" WIDTH="4096">&nbsp;
             </TD></TR>
            </TABLE>
        </TD>
    </TR>
    <TR>
        <TD>
        <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
        <TR>
            <TD>
                <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
                <TR>
                    <TD WIDTH="10"><IMG SRC="/i/hs/clear_10_pix_width.gif" WIDTH="10" HEIGHT="1" BORDER="0"></TD>
                </TR>
                </TABLE>
            </TD>
            <TD HEIGHT="100%" CLASS="bodyText">
            <!--Body starts here-->
					<P><BR></P>

                    <BR><B>1. STANDARD</B><BR>
The "Standard" editor was created as the default editor. It contains some basic
"windows" style editing features. The "ctrl" refers to the "Control" key.
                                <BR><BR><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD COLSPAN="5" CLASS="bodyText"><B>Key Commands</B></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="5" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="5" ALT=""></TD></TR><TR><TD CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="5" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>Ctrl-c</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Copy selected text to windows clipboard.
                                        </TD></TR><TR><TD CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="5" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>Ctrl-x</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Cut selected text from the editing buffer, and store in the windows clipboard.
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="5" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>Ctrl-v</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Paste text from the windows clipboard into the editing buffer.
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="1" HEIGHT="15" ALT=""></TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><B>Mouse Commands</B></TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="1" HEIGHT="5" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="5" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>Text selection</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Click and hold the the left mouse button at the beginning of your text
    block, and drag mouse to the right and down to the end of your text block.
                                        </TD></TR></TABLE><BR><BR><BR><B>2. JVI</B><BR>
The "JVI" editor, is a java implementation of the well known VI editor on the unix platform.
This editor is purely implemented in Java and contains a subset of the commands and
functionality of the original VI editor.
                                <BR><BR><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD COLSPAN="3" CLASS="bodyText"><B>Unimplemented features</B></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="5" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText">
                                            Anything involving named registers, such as buffers and setting marks
    in the document.
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText">
                                            All ":" commands.
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText">
                                            Regex engine for searches ( '/' '?' ) - all searches are
    executed exactly as typed.
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText">
                                            Anything related to macros.
                                        </TD></TR></TABLE><BR>
                                The rest of JVI has been implemented as closely to the original VI as possible including all
the required undo buffers, repeat command features, and complex command combinations such as
"repeat/command/motion command" i.e. "7dw", etc.
                                <BR><BR><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD COLSPAN="2" CLASS="bodyText"><B>Implemented features</B></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="12" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="12" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="10" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Motion commands</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>j</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Down
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>k</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Up
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>h</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Left
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>h</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Left
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>l</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Right
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>o</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Beginning of line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>$</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            End of line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            First non-whitespace character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>+</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            First character of next line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>-</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            First character of previous line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>spacebar</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Next character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>return</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Next line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>e</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            End of word
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>E</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            End of word, ignore punctuation
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>b</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Beginning of previous word
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>w</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Beginning of next word
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>W</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Beginning of next word, ignore punctuation
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>H</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            First line on screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>L</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Last line on screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>M</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Middle of Screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>G</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Goto (defaults to end of file)
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>%</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Find match of current parenthesis, brace, or bracket
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>(</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Previous sentence
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>)</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Next sentence
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>{</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Previous paragraph
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>}</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Next paragraph
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>[</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Previous section
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>]</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Next section
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^m</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Carriage return
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText"><B>^n</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Down in command
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText"><B>^j</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Down in command, create newline in insert
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^p</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Up in command
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^h</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText">
                                            Backspace in insert mode, left in command mode
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="1" ALT=""></TD></TR><TR><TD WIDTH="10" HEIGHT="1"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Insert Commands</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            i
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Insert before current location
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            I
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Insert before first non-whitespace character on line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            a
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Append after the current location
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            A
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Append at the end of the line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            o
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Open line below current
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD WIDTH="30" VALIGN="top" CLASS="bodyText">
                                            O
                                        </TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Open line above current
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="1" ALT=""></TD></TR><TR><TD WIDTH="10" HEIGHT="1" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Change Commands</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>~</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Switch case of current character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>c</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Change until...
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>C</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Change to end of line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>r</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Replace current character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>R</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Replace characters until insert mode is left
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>s</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Substitute
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>S</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Substitute entire line
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="1" ALT=""></TD></TR><TR><TD WIDTH="10" HEIGHT="1"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Cut/copy/paste/undo</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>x</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Delete current character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>X</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Delete previous character
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>d</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Delete until...
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>D</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Delete to end of line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>y</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Yank...
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>Y</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Yank current line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>p</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Put below current line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>P</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Put above current line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>u</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Undo last change
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>U</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Undo changes to current line
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="1" ALT=""></TD></TR><TR><TD WIDTH="10" HEIGHT="1"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Scrolling</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>z</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Reposition screen around line (\n to top of screen, . to middle, - to bottom)
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^b</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll back one screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^d</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll down half a window, moves to previous shift width in insert mode
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^e</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll screen down one line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^f</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll forward one screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^u</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll up half a window, in insert mode move to the beginning of insert mode
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^y</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Scroll screen up one line
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="1" ALT=""></TD></TR><TR><TD WIDTH="10" HEIGHT="1"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="1" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><B>Miscellaneous</B></TD></TR></TABLE><TABLE CELLSPACING="0" CELLPADDING="0" BORDER="0"><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="80" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="15" HEIGHT="8" ALT=""></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="100" HEIGHT="8" ALT=""></TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>#</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            (where # is a number) following command n times...
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>.</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Repeat last command
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>&lt;</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Shift one shiftwidth to the left
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>&gt;</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Shift one shiftwidth to the right
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>t</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Moves to next shiftwidth
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>J</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Join next line with current line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>g</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Show status line
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^l</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Redraw screen
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^r</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Redraw screen in command mode
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^c</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Ends insert mode, unused in command mode (if defined as interupt)
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^[</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Ends insert mode (ESCAPE)
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^i</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Tab in insert, unused in command
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^v</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Unused in command, quotes next character in insert
                                        </TD></TR><TR><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" WIDTH="10" HEIGHT="5" ALT=""></TD><TD VALIGN="top" ALIGN="center" CLASS="bodyText"><B>&middot;</B></TD><TD VALIGN="top" CLASS="bodyText"><B>^w</B></TD><TD VALIGN="top" CLASS="bodyText"><IMG BORDER="0" HEIGHT="5" WIDTH="15" SRC="/i/hs/clear.gif"></TD><TD VALIGN="top" CLASS="bodyText">
                                            Unused in command, in insert move back to beginning of previous word
                                        </TD></TR><TR><TD VALIGN="top" COLSPAN="5" CLASS="bodyText"><IMG BORDER="0" SRC="/i/hs/clear.gif" ALT="" HEIGHT="15" WIDTH="1"></TD></TR></TABLE><P><BR></P>
              <!--Body Ends Here-->
            </TD>
             <TD>
                <TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
                 <TR>
                    <TD WIDTH="10"><IMG SRC="/i/hs/clear_10_pix_width.gif" WIDTH="10" HEIGHT="1" BORDER="0"></TD>
                 </TR>
                </TABLE>
            </TD>
           </TR>
          </TABLE>
         </TD>
        </TR>

       </TABLE>
        </TD>
        <TD WIDTH="1" BGCOLOR="#000000" VALIGN="top"><IMG SRC="/i/hs/frame_1pix_bg_lg_top.gif" WIDTH="1" HEIGHT="18" ALT="" BORDER="0"></TD>
        <TD WIDTH="1" BGCOLOR="#C5C5C9" VALIGN="top"><IMG SRC="/i/hs/frame_1pix_bg_lg_top_right.gif" WIDTH="1" HEIGHT="18" ALT="" BORDER="0"></TD>
        <TD WIDTH="" BGCOLOR="#001934" VALIGN="top">
<IMG SRC="/i/hs/right_top_3dots.gif" WIDTH="86" HEIGHT="41" ALT="" BORDER="0" >
<BR>
<jsp:include page="../includes/right_resources.jsp" /></TD>
	</TR>
</TABLE>
</TD></TR></TABLE>
<jsp:include page="../includes/foot.jsp" />
</BODY>
</HTML>
