services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: appiriodevops/openjdk7:buildv1
    platform: linux/amd64
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock


