#!/bin/ksh

java -cp "/home/coder/resources/ifxjdbc.jar:/home/coder/resources/jdbc7.0-1.2.jar:/home/coder/resources/xerces.jar:/home/coder/classes" com.topcoder.utilities.dwload.TCLoadUtility -xmlfile /home/coder/resources/stat/dwload/loadcoders.xml

