<%@  page language="java"  %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>TopCoder Tournaments</title>

<jsp:include page="/script.jsp" />
<jsp:include page="/style.jsp">
  <jsp:param name="key" value="tc_main"/>
</jsp:include>
<script language="JavaScript">
  function changeImage(image, newImage) {
    document[image].src=newImage;
    return;
  }
</script>
</head>

<body>

<jsp:include page="/top.jsp" >
    <jsp:param name="level1" value=""/>
</jsp:include>

<table width="100%" border="0" cellpadding="0" cellspacing="0">
   <tr valign="top">
<!-- Left Column Begins-->
        <td width="180">
            <jsp:include page="/includes/global_left.jsp">
                <jsp:param name="node" value="topcoder_tournaments"/>
            </jsp:include>
        </td>
<!-- Left Column Ends -->

<!-- Center Column Begins -->
<TD class="bodyText" width="100%" valign="top">
<div align="center" style="margin: 0px 10px 0px 10px;">


<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%">
  <TR>
    <TD BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" VALIGN="top" WIDTH="11"><IMG SRC="/i/clear.gif" ALT="" WIDTH="11" HEIGHT="1" BORDER="0"/></TD>
    <TD COLSPAN="2" VALIGN="top" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%"><IMG SRC="/i/clear.gif" ALT="" WIDTH="240" HEIGHT="1" BORDER="0"/><br>

            <jsp:include page="links.jsp" />
            <jsp:include page="links_rules.jsp" />

  <br><br>
<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
                    <TR>
                      <TD COLSPAN="4" VALIGN="middle" HEIGHT="18" CLASS="statTextBig" BACKGROUND="/i/steel_gray_bg.gif">&#160;&#160;qubits Breakdown</TD>
                    </TR>
                    </TABLE><BR/>                
                    
       <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
       <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Seed</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Handle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Rating</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Vol.</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Avg. Award</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$1,250</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$2,500</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$4,000</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$10,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$15,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$20,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$50,000</B></FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">1</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">SnapDragon</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3151</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">433</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$19400.66</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.36%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">2</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">reid</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3085</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">390</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16971.31</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.9%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">3</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">NDBronson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2988</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">441</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$15971.35</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.30%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.2%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">4</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">John Dethridge</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3079</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">404</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$13958.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.67%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">38.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.31%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">5</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ZorbaTHut</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3132</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">274</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16361.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.631%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.10%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">6</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">radeye</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2732</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$7019.69</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">45.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.21%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.22%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.15%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">7</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dmwright</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2785</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">350</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6486.43</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">42.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.81%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.44%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">8</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">malpt</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2617</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">491</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$5059.46</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">36.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.11%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.45%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.71%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">9</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ambrose</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2693</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">543</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6346.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">30.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">34.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">8.85%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.66%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.29%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">10</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dgarthur</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2501</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4107.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">39.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">20.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.04%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.64%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.967%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">11</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">obfuscator</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2434</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">320</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$3328.17</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">48.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.50%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.582%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.124%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">12</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">DjinnKahn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2576</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">325</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2992.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">54.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.87%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.40%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.711%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.245%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">13</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jms137</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2299</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">285</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1707.68</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">71.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.70%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.267%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.100%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.026%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.004%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">14</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">moira</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2065</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">437</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1965.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">70.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">19.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.79%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.03%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.393%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.085%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.021%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">15</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">lars</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2117</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">629</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$2483.56</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">62.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">21.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.28%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.937%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.399%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.227%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">16</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">kyky</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2070</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">401</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1838.72</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">68.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">23.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.97%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.833%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.151%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.032%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.005%</FONT></TD></TR>
</TABLE>
<BR/>
      <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
<TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Seed</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Handle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Rating</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Vol.</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Avg. Award</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$1,250</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$2,500</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$4,000</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$10,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$15,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$20,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$50,000</B></FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">1</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">SnapDragon</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3151</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">433</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$19400.66</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.36%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">8</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">malpt</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2617</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">491</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$5059.46</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">36.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.11%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.45%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.71%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">9</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ambrose</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2693</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">543</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6346.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">30.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">34.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">8.85%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.66%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.29%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">16</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">kyky</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2070</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">401</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1838.72</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">68.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">23.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.97%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.833%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.151%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.032%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.005%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">2</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">reid</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3085</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">390</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16971.31</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.9%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">7</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dmwright</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2785</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">350</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6486.43</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">42.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.81%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.44%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">10</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dgarthur</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2501</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4107.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">39.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">20.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.04%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.64%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.967%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">15</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">lars</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2117</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">629</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$2483.56</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">62.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">21.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.28%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.937%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.399%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.227%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">3</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">NDBronson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2988</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">441</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$15971.35</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.30%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.2%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">6</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">radeye</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2732</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$7019.69</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">45.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.21%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.22%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.15%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">11</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">obfuscator</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2434</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">320</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$3328.17</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">48.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.50%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.582%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.124%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">14</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">moira</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2065</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">437</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1965.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">70.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">19.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.79%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.03%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.393%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.085%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.021%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">4</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">John Dethridge</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3079</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">404</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$13958.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.67%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">38.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.31%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">5</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ZorbaTHut</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3132</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">274</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16361.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.631%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.10%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">12</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">DjinnKahn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2576</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">325</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2992.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">54.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.87%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.40%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.711%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.245%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">13</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jms137</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2299</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">285</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1707.68</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">71.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.70%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.267%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.100%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.026%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.004%</FONT></TD></TR>
</TABLE>
<BR/><IMG SRC="/i/m/qubits_mug.gif" ALT="" WIDTH="55" HEIGHT="61" BORDER="0" HSPACE="6" VSPACE="1" ALIGN="left"/>
By&#160;qubits<BR/><DIV><I>TopCoder Member</I><BR/><A HREF="/tc?module=MemberProfile&cr=105922"><FONT COLOR="#FFFFFF"> Author Profile</FONT></A></DIV><BR CLEAR="all"/><BR/>

      </TD>
   </TR>
</TABLE>

   <br><br>
</div>
</td>
<!-- Center Column Ends -->

<!-- Right Column Begins -->
         <td width="170">
            <jsp:include page="/public_right.jsp">
               <jsp:param name="level1" value="default"/>
            </jsp:include>
         </td>
<!-- Right Column Ends -->

<!-- Gutter -->
         <td width="10"><img src="/i/clear.gif" width="10" height="1" border="0"></td>
<!-- Gutter Ends -->
    </tr>
</table>

<jsp:include page="/foot.jsp" />

</body>

</html>
