<%@  page language="java"  %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>TopCoder Tournaments</title>

<jsp:include page="/script.jsp" />
<jsp:include page="/style.jsp">
  <jsp:param name="key" value="tc_main"/>
</jsp:include>
<script language="JavaScript">
  function changeImage(image, newImage) {
    document[image].src=newImage;
    return;
  }
</script>
</head>

<body>

<jsp:include page="/top.jsp" >
    <jsp:param name="level1" value=""/>
</jsp:include>

<table width="100%" border="0" cellpadding="0" cellspacing="0">
   <tr valign="top">
<!-- Left Column Begins-->
        <td width="180">
            <jsp:include page="/includes/global_left.jsp">
                <jsp:param name="node" value="topcoder_tournaments"/>
            </jsp:include>
        </td>
<!-- Left Column Ends -->

<!-- Center Column Begins -->
<TD class="bodyText" width="100%" valign="top">
<div align="center" style="margin: 0px 10px 0px 10px;">


<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%">
  <TR>
    <TD BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" VALIGN="top" WIDTH="11"><IMG SRC="/i/clear.gif" ALT="" WIDTH="11" HEIGHT="1" BORDER="0"/></TD>
    <TD COLSPAN="2" VALIGN="top" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%"><IMG SRC="/i/clear.gif" ALT="" WIDTH="240" HEIGHT="1" BORDER="0"/><br>

            <jsp:include page="links.jsp" />
            <jsp:include page="links_rules.jsp" />

  <br><br>
<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
                    <TR>
                      <TD COLSPAN="4" VALIGN="middle" HEIGHT="18" CLASS="statTextBig" BACKGROUND="/i/steel_gray_bg.gif">&#160;&#160;qubits Breakdown</TD>
                    </TR>
                    </TABLE><BR/>                
                    
       <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
<TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Seed</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Handle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Rating</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Vol.</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Avg. Award</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Round 4</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Semis</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Finals</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">1</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">SnapDragon</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3121</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">359</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$20488.43</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">92.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">68.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">2</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">reid</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3129</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">412</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$19587.13</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">90.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">64.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.3%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">3</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">NDBronson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2999</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">479</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$13219.46</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">80.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">48.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">4</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">John Dethridge</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3001</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">428</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$11890.97</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">83.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.6%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">5</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ZorbaTHut</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3062</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">296</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$15891.86</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">94.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">55.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.8%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">6</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">radeye</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2725</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">343</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4582.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">64.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.59%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">7</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">bigg_nate</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2740</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">271</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4703.48</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">70.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.29%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">8</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dmwright</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2732</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">355</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4450.22</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">65.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.63%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">9</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">doeth</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2563</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">355</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2338.01</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">46.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.60%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.337%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">10</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">malpt</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2550</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">506</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2640.85</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">46.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.52%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.800%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">11</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ambrose</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2589</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">580</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$3186.88</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">49.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.87%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.42%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">12</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dgarthur</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2367</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">472</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1450.67</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">31.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.62%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.139%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">13</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">obfuscator</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2342</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">275</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$919.34</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.494%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.007%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">14</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">DjinnKahn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2543</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">343</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2071.34</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">44.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.33%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.229%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">15</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ante</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2373</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">489</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1493.83</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.93%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.162%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">16</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">milhouse</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2349</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">480</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1376.49</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">30.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.128%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">17</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jonmac</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2405</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">417</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1433.74</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.49%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.108%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">18</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">uglyfool</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2551</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2013.39</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">44.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.17%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.208%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">19</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">kpsmith</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2412</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">318</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1200.49</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">28.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.37%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.035%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">20</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">WishingBone</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2463</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">622</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2247.37</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.63%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.750%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">21</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">po</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2256</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">390</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$888.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">19.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.694%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.014%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">22</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dvickrey</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2205</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">273</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$630.47</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.94%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.087%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">23</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">Brian</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2330</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">361</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1003.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.952%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.019%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">24</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">Alexandre</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2218</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">259</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$623.48</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.60%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.074%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">25</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">kv</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2252</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">353</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$810.91</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.441%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.007%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">26</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">Joe</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2089</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">412</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$672.60</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.206%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.002%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">27</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">daveagp</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2384</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1521.29</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">33.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.36%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.210%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">28</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">gilbert</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2245</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">538</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1116.01</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.83%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.079%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">29</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">KurtSteinkraus</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2293</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">342</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$865.34</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.572%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.008%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">30</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">along</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2346</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">430</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1184.73</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">28.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.82%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.062%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">31</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">Ken Alverson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2233</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">360</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$783.24</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.416%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.005%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">32</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">zoidal</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2273</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">412</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$948.62</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.957%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.022%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">33</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jms137</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2288</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">292</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$770.34</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.322%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.002%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">34</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">halflife</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2218</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">405</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$828.85</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.600%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.010%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">35</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">moira</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1963</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">428</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$594.40</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.99%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.088%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">36</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">lars</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1962</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">683</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$839.03</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">17.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.998%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.033%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">37</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">eduar09</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2156</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">353</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$671.12</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.187%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.002%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">38</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">Wasteland</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2232</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">554</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1120.96</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.90%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.091%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">39</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dsp</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2220</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">570</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1118.74</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.91%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.093%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">40</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dangelo</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2376</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">556</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1592.01</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">34.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.78%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.274%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">41</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">ShakeSpace</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2023</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">328</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$554.48</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.19%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.023%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">42</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">PurpleBob</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1886</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">362</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$529.58</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.57%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.010%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">43</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">anr</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2306</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">493</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1195.26</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.95%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.090%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">44</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">axch</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2126</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">381</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$673.19</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.187%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.002%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">45</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">schveiguy</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2052</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">368</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$600.21</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.05%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.076%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">46</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">loopy</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2210</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">482</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$938.82</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.983%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.030%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">47</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">BigDaddy</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1819</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">283</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$503.74</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.369%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">48</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">kyky</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1913</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">388</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$548.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">3.97%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.023%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">49</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">claw</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1657</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">359</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$504.58</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.485%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">50</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">legakis</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2034</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">398</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$614.72</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.94%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.102%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">51</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">tjq</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1741</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">534</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$565.55</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">5.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.056%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">52</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">Abednego</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1826</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">454</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$554.08</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.51%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.032%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">53</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">cbthiess</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1770</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">411</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$524.73</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.27%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.007%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">54</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">O_O</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1711</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$503.60</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.377%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">55</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">madking</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1832</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">511</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$586.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.73%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.082%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">56</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">jfreyss</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1776</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">328</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$507.07</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.701%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">57</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">maxx</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1949</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">417</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$580.10</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.06%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.053%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">58</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">gladius</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1760</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">423</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$526.61</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.008%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">59</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">FunOrPain</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1904</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">415</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$560.02</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.79%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.031%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">60</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">Mr. Sketch</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1649</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">369</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$505.34</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.555%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">61</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">Smiley=)</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1649</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">428</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$513.82</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1.39%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.003%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">62</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">amorosov</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1610</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">402</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$507.04</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.742%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">63</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">Frostburn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1812</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">542</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$596.07</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.37%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.099%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.001%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">64</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">mortijingle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">1647</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$534.40</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">3.19%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.017%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.000%</FONT></TD></TR>
</TABLE>
<BR/><IMG SRC="/i/m/qubits_mug.gif" ALT="" WIDTH="55" HEIGHT="61" BORDER="0" HSPACE="6" VSPACE="1" ALIGN="left"/>
By&#160;qubits<BR/><DIV><I>TopCoder Member</I><BR/><A HREF="/tc?module=MemberProfile&cr=105922"><FONT COLOR="#FFFFFF"> Author Profile</FONT></A></DIV><BR CLEAR="all"/><BR/>

      </TD>
   </TR>
</TABLE>

   <br><br>
</div>
</td>
<!-- Center Column Ends -->

<!-- Right Column Begins -->
         <td width="170">
            <jsp:include page="/public_right.jsp">
               <jsp:param name="level1" value="default"/>
            </jsp:include>
         </td>
<!-- Right Column Ends -->

<!-- Gutter -->
         <td width="10"><img src="/i/clear.gif" width="10" height="1" border="0"></td>
<!-- Gutter Ends -->
    </tr>
</table>

<jsp:include page="/foot.jsp" />

</body>

</html>
