DROP TABLE PROJECT;
DROP TABLE PHASE_INSTANCE;
DROP TABLE R_USER_ROLE;
DROP TABLE PAYMENT_INFO;

DROP TABLE PAYMENT_STATUS;
DROP TABLE PROJECT_STATUS;
DROP TABLE PROJECT_TYPE;
DROP TABLE REVIEW_PHASE;
DROP TABLE REVIEW_ROLE;
DROP TABLE REVIEW_RESP;


DROP TABLE SCORECARD;
DROP TABLE SUBMISSION;
DROP TABLE AGG_WORKSHEET;
DROP TABLE AGG_REVIEW;
DROP TABLE TESTCASE_REVIEW;
DROP TABLE FINAL_REVIEW;

DROP TABLE AGG_RESPONSE;
DROP TABLE SUBJECTIVE_RESP;
DROP TABLE FIX_ITEM;
DROP TABLE SCORECARD_QUESTION;
DROP TABLE TESTCASE_QUESTION;
DROP TABLE QUESTION_TEMPLATE;

DROP TABLE AGG_APPROVAL;
DROP TABLE AGG_RESP_STAT;
DROP TABLE EVALUATION;
DROP TABLE EVALUATION_TYPE;
DROP TABLE FINAL_FIX_STATUS;
DROP TABLE RESPONSE_TYPE;
DROP TABLE SCORECARD_SECTION;
DROP TABLE SC_SECTION_GROUP;
DROP TABLE TESTCASE_APPROVAL;


-- ProjectTracker tables

CREATE TABLE PROJECT (
    PROJECT_V_ID       SERIAL8 NOT NULL,
    PROJECT_ID         DEC(18) NOT NULL,
    COMP_VERS_ID       DEC(18) NOT NULL,
    PHASE_INSTANCE_ID  DEC(18) NOT NULL,
    WINNER_ID          DEC(18),
    OVERVIEW           LVARCHAR,
    NOTES              LVARCHAR,
    PROJECT_TYPE_ID    DEC(18) NOT NULL,
    PROJECT_STAT_ID    DEC(18) NOT NULL,
    NOTIFICATION_SENT  DEC(1) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    MODIFY_REASON      LVARCHAR,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE PROJECT
    ADD CONSTRAINT PRIMARY KEY (PROJECT_V_ID);


CREATE TABLE PHASE_INSTANCE (
    PHASE_INST_V_ID    SERIAL8 NOT NULL,
    PHASE_INSTANCE_ID  DEC(18) NOT NULL,
    START_DATE         DATE,
    END_DATE           DATE,
    PHASE_ID           DEC(18) NOT NULL,
    PROJECT_ID         DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE PHASE_INSTANCE
    ADD CONSTRAINT PRIMARY KEY (PHASE_INST_V_ID);


CREATE TABLE R_USER_ROLE (
    R_USER_ROLE_V_ID   SERIAL8 NOT NULL,
    R_USER_ROLE_ID     DEC(18) NOT NULL,
	R_ROLE_ID          DEC(18) NOT NULL,
    PROJECT_ID         DEC(18) NOT NULL,
    LOGIN_ID           DEC(18),
    PAYMENT_INFO_ID    DEC(18),
    R_RESP_ID          DEC(18),
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE R_USER_ROLE
    ADD CONSTRAINT PRIMARY KEY (R_USER_ROLE_V_ID);


CREATE TABLE PAYMENT_INFO (
    PAYMENT_INFO_V_ID  SERIAL8 NOT NULL,
    PAYMENT_INFO_ID    DEC(18) NOT NULL,
    PAYMENT            MONEY(10,2) NOT NULL,
    PAYMENT_STAT_ID    DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE PAYMENT_INFO
    ADD CONSTRAINT PRIMARY KEY (PAYMENT_INFO_V_ID);




CREATE TABLE PAYMENT_STATUS (
    PAYMENT_STAT_ID    DEC(18) NOT NULL,
    PAYMENT_STAT_NAME  VARCHAR(254) NOT NULL
);

ALTER TABLE PAYMENT_STATUS
    ADD CONSTRAINT PRIMARY KEY (PAYMENT_STAT_ID);


CREATE TABLE PROJECT_STATUS (
    PROJECT_STAT_ID    DEC(18) NOT NULL,
    PROJECT_STAT_NAME  VARCHAR(254) NOT NULL
);

ALTER TABLE PROJECT_STATUS
    ADD CONSTRAINT PRIMARY KEY (PROJECT_STAT_ID);


CREATE TABLE PROJECT_TYPE (
    PROJECT_TYPE_ID    DEC(18) NOT NULL,
    PROJECT_TYPE_NAME  VARCHAR(254) NOT NULL
);

ALTER TABLE PROJECT_TYPE
    ADD CONSTRAINT PRIMARY KEY (PROJECT_TYPE_ID);
	

CREATE TABLE REVIEW_RESP (
    REVIEW_RESP_ID     DEC(18) NOT NULL,
    REVIEW_RESP_NAME   VARCHAR(254) NOT NULL
);

ALTER TABLE REVIEW_RESP
    ADD CONSTRAINT PRIMARY KEY (REVIEW_RESP_ID);


CREATE TABLE REVIEW_PHASE (
    REVIEW_PHASE_ID    DEC(18) NOT NULL,
    REVIEW_PHASE_NAME  VARCHAR(254) NOT NULL
);

ALTER TABLE REVIEW_PHASE
    ADD CONSTRAINT PRIMARY KEY (REVIEW_PHASE_ID);


CREATE TABLE REVIEW_ROLE (
    REVIEW_ROLE_ID     DEC(18) NOT NULL,
    REVIEW_ROLE_NAME   VARCHAR(254) NOT NULL
);

ALTER TABLE REVIEW_ROLE
    ADD CONSTRAINT PRIMARY KEY (REVIEW_ROLE_ID);


-- ProjectTracker foreign key constraints

ALTER TABLE PROJECT
    ADD CONSTRAINT FOREIGN KEY (COMP_VERS_ID)
        REFERENCES COMP_VERSIONS (COMP_VERS_ID);
  --ALTER TABLE PROJECT
  --    ADD CONSTRAINT FOREIGN KEY (PHASE_INSTANCE_ID)
  --       REFERENCES PHASE_INSTANCE (PHASE_INSTANCE_ID);
--ALTER TABLE PROJECT
--    ADD CONSTRAINT FOREIGN KEY (WINNER_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
ALTER TABLE PROJECT
    ADD CONSTRAINT FOREIGN KEY (PROJECT_TYPE_ID)
       REFERENCES PROJECT_TYPE (PROJECT_TYPE_ID);
ALTER TABLE PROJECT
    ADD CONSTRAINT FOREIGN KEY (PROJECT_STAT_ID)
       REFERENCES PROJECT_STATUS (PROJECT_STAT_ID);
--ALTER TABLE PROJECT
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE PHASE_INSTANCE
    ADD CONSTRAINT FOREIGN KEY (PHASE_ID)
       REFERENCES REVIEW_PHASE (REVIEW_PHASE_ID);
  --ALTER TABLE PHASE_INSTANCE
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
--ALTER TABLE PHASE_INSTANCE
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE R_USER_ROLE
    ADD CONSTRAINT FOREIGN KEY (R_ROLE_ID)
       REFERENCES REVIEW_ROLE (REVIEW_ROLE_ID);
  --ALTER TABLE R_USER_ROLE
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
--ALTER TABLE R_USER_ROLE
--    ADD CONSTRAINT FOREIGN KEY (LOGIN_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
  --ALTER TABLE R_USER_ROLE
  --    ADD CONSTRAINT FOREIGN KEY (PAYMENT_INFO_ID)
  --       REFERENCES PAYMENT_INFO (PAYMENT_INFO_ID);
ALTER TABLE R_USER_ROLE
    ADD CONSTRAINT FOREIGN KEY (R_RESP_ID)
       REFERENCES REVIEW_RESP (REVIEW_RESP_ID);
--ALTER TABLE R_USER_ROLE
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE PAYMENT_INFO
    ADD CONSTRAINT FOREIGN KEY (PAYMENT_STAT_ID)
       REFERENCES PAYMENT_STATUS (PAYMENT_STAT_ID);
--ALTER TABLE PAYMENT_INFO
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);





-- DocumentManager tables

CREATE TABLE SCORECARD (
    SCORECARD_V_ID     SERIAL8 NOT NULL,
 	SCORECARD_ID       DEC(18) NOT NULL,
 	SCORECARD_TYPE     DEC(7) NOT NULL,
 	IS_COMPLETED       DEC(1) NOT NULL,
 	IS_PM_REVIEWED     DEC(1) NOT NULL,
 	AUTHOR_ID          DEC(18) NOT NULL,
 	PROJECT_ID         DEC(18) NOT NULL,
 	SUBMISSION_ID      DEC(18) NOT NULL,
 	SCORE              FLOAT NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);
ALTER TABLE SCORECARD
    ADD CONSTRAINT PRIMARY KEY (SCORECARD_V_ID);


CREATE TABLE SUBMISSION (
    SUBMISSION_V_ID    SERIAL8 NOT NULL,
    SUBMISSION_ID      DEC(18) NOT NULL,
    SUBMISSION_TYPE    DEC(7) NOT NULL,
    SUBMISSION_URL     LVARCHAR NOT NULL,
    SUB_PM_REVIEW_MSG  LVARCHAR,
    SUB_PM_SCREEN_MSG  LVARCHAR,
    SUBMITTER_ID       DEC(18) NOT NULL,
    PROJECT_ID         DEC(18) NOT NULL,
    IS_REMOVED         DEC(1) NOT NULL,
    SUBMISSION_DATE    DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE SUBMISSION
    ADD CONSTRAINT PRIMARY KEY (SUBMISSION_V_ID);

CREATE TABLE TESTCASE_REVIEW (
    REVIEW_V_ID        SERIAL8 NOT NULL,
    REVIEW_ID          DEC(18) NOT NULL,
    TESTCASE_APP_ID    DEC(18),
    REVIEW_TEXT        LVARCHAR,
    PROJECT_ID         DEC(18) NOT NULL,
    REVIEWER_ID        DEC(18) NOT NULL,
    REVIEWEE_ID        DEC(18) NOT NULL,
    IS_COMPLETED       DEC(1) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE TESTCASE_REVIEW
    ADD CONSTRAINT PRIMARY KEY (REVIEW_V_ID);


CREATE TABLE AGG_WORKSHEET (
    AGG_WORKSHEET_V_ID SERIAL8 NOT NULL,
    AGG_WORKSHEET_ID   DEC(18) NOT NULL,
    IS_COMPLETED       DEC(1) NOT NULL,
    IS_PM_REVIEWED     DEC(1) NOT NULL,
    AGGREGATOR_ID      DEC(18) NOT NULL,	
    PROJECT_ID         DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE AGG_WORKSHEET
    ADD CONSTRAINT PRIMARY KEY (AGG_WORKSHEET_V_ID);


CREATE TABLE AGG_REVIEW (
    AGG_REVIEW_V_ID    SERIAL8 NOT NULL,
    AGG_REVIEW_ID      DEC(18) NOT NULL,
    AGG_APPROVAL_ID    DEC(18),
    AGG_REVIEW_TEXT    LVARCHAR,
    IS_PM_REVIEWED     DEC(1) NOT NULL,
    AGG_WORKSHEET_ID   DEC(18) NOT NULL,
    IS_COMPLETED       DEC(1) NOT NULL,
    REVIEWER_ID        DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE AGG_REVIEW
    ADD CONSTRAINT PRIMARY KEY (AGG_REVIEW_V_ID);


CREATE TABLE FINAL_REVIEW (
    FINAL_REVIEW_V_ID  SERIAL8 NOT NULL,
    FINAL_REVIEW_ID    DEC(18) NOT NULL,
    AGG_WORKSHEET_ID   DEC(18) NOT NULL,
    IS_COMPLETED       DEC(1) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE FINAL_REVIEW
    ADD CONSTRAINT PRIMARY KEY (FINAL_REVIEW_V_ID);


CREATE TABLE AGG_RESPONSE (
    AGG_RESPONSE_V_ID  SERIAL8 NOT NULL,
    AGG_RESPONSE_ID    DEC(18) NOT NULL,
    SUBJECTIVE_RESP_ID DEC(18) NOT NULL,
    AGG_RESP_STAT_ID   DEC(18),
    AGG_WORKSHEET_ID   DEC(18) NOT NULL,
    RESPONSE_TEXT      TEXT,
    RESPONSE_TYPE_ID   DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE AGG_RESPONSE
    ADD CONSTRAINT PRIMARY KEY (AGG_RESPONSE_V_ID);


CREATE TABLE SUBJECTIVE_RESP (
    SUBJECTIVE_R_V_ID  SERIAL8 NOT NULL,
    SUBJECTIVE_RESP_ID DEC(18) NOT NULL,
    RESPONSE_TEXT      TEXT,
    RESPONSE_TYPE_ID   DEC(18) NOT NULL,
    QUESTION_ID        DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE SUBJECTIVE_RESP
    ADD CONSTRAINT PRIMARY KEY (SUBJECTIVE_R_V_ID);


CREATE TABLE FIX_ITEM (
    FIX_ITEM_V_ID      SERIAL8 NOT NULL,
    FIX_ITEM_ID        DEC(18) NOT NULL,
    FINAL_FIX_S_ID     DEC(18),
    AGG_RESPONSE_ID    DEC(18) NOT NULL,
    FINAL_REVIEW_ID    DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE FIX_ITEM
    ADD CONSTRAINT PRIMARY KEY (FIX_ITEM_V_ID);


CREATE TABLE SCORECARD_QUESTION (
    QUESTION_V_ID      SERIAL8 NOT NULL,
    QUESTION_ID        DEC(18) NOT NULL,
    Q_TEMPLATE_V_ID    DEC(18) NOT NULL,
    EVALUATION_ID      DEC(18),
    SCORECARD_ID       DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE SCORECARD_QUESTION
    ADD CONSTRAINT PRIMARY KEY (QUESTION_V_ID);


CREATE TABLE TESTCASE_QUESTION (
    TC_QUESTION_V_ID   SERIAL8 NOT NULL,
    QUESTION_ID        DEC(18) NOT NULL,
    TOTAL_TESTS        DEC(7) NOT NULL,
    TOTAL_PASS         DEC(7) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE TESTCASE_QUESTION
    ADD CONSTRAINT PRIMARY KEY (TC_QUESTION_V_ID);


CREATE TABLE QUESTION_TEMPLATE (
    Q_TEMPLATE_V_ID    SERIAL8 NOT NULL,
    Q_TEMPLATE_ID      DEC(18) NOT NULL,
    PROJECT_TYPE       DEC(18) NOT NULL,
    SCORECARD_TYPE     DEC(7) NOT NULL,
    QUESTION_TEXT      LVARCHAR NOT NULL,
    QUESTION_WEIGHT    DEC(7) NOT NULL,
    QUESTION_SEQ_LOC   DEC(7) NOT NULL,
    SECTION_ID         DEC(18) NOT NULL,
    QUESTION_TYPE      DEC(7) NOT NULL,
    TEMPLATE_ID        DEC(18) NOT NULL,
    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
    MODIFY_USER        DEC(18) NOT NULL,
    CUR_VERSION        DEC(1) NOT NULL
);

ALTER TABLE QUESTION_TEMPLATE
    ADD CONSTRAINT PRIMARY KEY (Q_TEMPLATE_V_ID);


CREATE TABLE PROJECT_TEMPLATE (
    PT_ID              SERIAL8 NOT NULL,
    PROJECT_ID         DEC(18) NOT NULL,
    SCORECARD_TYPE     DEC(7) NOT NULL,
    TEMPLATE_ID        DEC(18) NOT NULL
);

ALTER TABLE PROJECT_TEMPLATE
    ADD CONSTRAINT PRIMARY KEY (PT_ID);

CREATE TABLE CURRENT_TEMPLATE (
    CT_ID              SERIAL8 NOT NULL,
    PROJECT_TYPE_ID    DEC(18) NOT NULL,
    SCORECARD_TYPE     DEC(7) NOT NULL,
    TEMPLATE_ID        DEC(18) NOT NULL
);

ALTER TABLE CURRENT_TEMPLATE
    ADD CONSTRAINT PRIMARY KEY (CT_ID);



-- DocumentManager "constants"
CREATE TABLE AGG_APPROVAL (
    AGG_APPROVAL_ID    DEC(18) NOT NULL,
    AGG_APPROVAL_NAME  LVARCHAR NOT NULL
);

ALTER TABLE AGG_APPROVAL
    ADD CONSTRAINT PRIMARY KEY (AGG_APPROVAL_ID);



CREATE TABLE AGG_RESP_STAT (
    AGG_RESP_STAT_ID   DEC(18) NOT NULL,
    AGG_RESP_STAT_NAME LVARCHAR NOT NULL
);

ALTER TABLE AGG_RESP_STAT
    ADD CONSTRAINT PRIMARY KEY (AGG_RESP_STAT_ID);



CREATE TABLE EVALUATION (
    EVALUATION_ID      DEC(18) NOT NULL,
    EVALUATION_NAME    LVARCHAR NOT NULL,
    VALUE              FLOAT NOT NULL,
    EVALUATION_TYPE_ID DEC(18) NOT NULL
);

ALTER TABLE EVALUATION
    ADD CONSTRAINT PRIMARY KEY (EVALUATION_ID);


CREATE TABLE EVALUATION_TYPE (
    EVALUATION_TYPE_ID DEC(18) NOT NULL,
    EVAL_TYPE_NAME     LVARCHAR NOT NULL
);

ALTER TABLE EVALUATION_TYPE
    ADD CONSTRAINT PRIMARY KEY (EVALUATION_TYPE_ID);
    


CREATE TABLE FINAL_FIX_STATUS (
    FINAL_FIX_S_ID     DEC(18) NOT NULL,
    FINAL_FIX_S_NAME   LVARCHAR NOT NULL
);

ALTER TABLE FINAL_FIX_STATUS
    ADD CONSTRAINT PRIMARY KEY (FINAL_FIX_S_ID);



CREATE TABLE RESPONSE_TYPE (
    RESPONSE_TYPE_ID   DEC(18) NOT NULL,
    RESPONSE_TYPE_NAME LVARCHAR NOT NULL
);

ALTER TABLE RESPONSE_TYPE
    ADD CONSTRAINT PRIMARY KEY (RESPONSE_TYPE_ID);



CREATE TABLE SCORECARD_SECTION (
    SECTION_ID         DEC(18) NOT NULL,
    SECTION_NAME       LVARCHAR NOT NULL,
    SECTION_WEIGHT     DEC(7) NOT NULL,
    SECTION_SEQ_LOC    DEC(7) NOT NULL,
	GROUP_ID           DEC(18) NOT NULL
);

ALTER TABLE SCORECARD_SECTION
    ADD CONSTRAINT PRIMARY KEY (SECTION_ID);


CREATE TABLE SC_SECTION_GROUP (
    GROUP_ID           DEC(18) NOT NULL,
    GROUP_NAME         LVARCHAR NOT NULL,
    GROUP_SEQ_LOC      DEC(7) NOT NULL
);

ALTER TABLE SC_SECTION_GROUP
    ADD CONSTRAINT PRIMARY KEY (GROUP_ID);


CREATE TABLE TESTCASE_APPROVAL (
    TESTCASE_APP_ID    DEC(18) NOT NULL,
    TESTCASE_APP_NAME  LVARCHAR NOT NULL
);

ALTER TABLE TESTCASE_APPROVAL
    ADD CONSTRAINT PRIMARY KEY (TESTCASE_APP_ID);

-- Document Manager foreign key constraints

--ALTER TABLE SCORECARD
--    ADD CONSTRAINT FOREIGN KEY (AUTHOR_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
  --ALTER TABLE SCORECARD
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
  --ALTER TABLE SCORECARD
  --    ADD CONSTRAINT FOREIGN KEY (SUBMISSION_ID))
  --       REFERENCES SUBMISSION (SUBMISSION_ID);
--ALTER TABLE SCORECARD
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

--ALTER TABLE SUBMISSION
--    ADD CONSTRAINT FOREIGN KEY (SUBMITTER_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
  --ALTER TABLE SUBMISSION
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
--ALTER TABLE SUBMISSION
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE TESTCASE_REVIEW
    ADD CONSTRAINT FOREIGN KEY (TESTCASE_APP_ID)
       REFERENCES TESTCASE_APPROVAL (TESTCASE_APP_ID);
  --ALTER TABLE TESTCASE_REVIEW
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
--ALTER TABLE TESTCASE_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (REVIEWER_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
--ALTER TABLE TESTCASE_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (REVIEWEE_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
--ALTER TABLE TESTCASE_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

--ALTER TABLE AGG_WORKSHEET
--    ADD CONSTRAINT FOREIGN KEY (AGGREGATOR_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
  --ALTER TABLE AGG_WORKSHEET
  --    ADD CONSTRAINT FOREIGN KEY (PROJECT_ID)
  --       REFERENCES PROJECT (PROJECT_ID);
--ALTER TABLE AGG_WORKSHEET
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE AGG_REVIEW
    ADD CONSTRAINT FOREIGN KEY (AGG_APPROVAL_ID)
       REFERENCES AGG_APPROVAL (AGG_APPROVAL_ID);
  --ALTER TABLE AGG_REVIEW
  --    ADD CONSTRAINT FOREIGN KEY (AGG_WORKSHEET_ID)
  --       REFERENCES AGG_WORKSHEET (AGG_WORKSHEET_ID);
--ALTER TABLE AGG_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (REVIEWER_ID)
--       REFERENCES SECURITY_USER (LOGIN_ID);
--ALTER TABLE AGG_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

  --ALTER TABLE FINAL_REVIEW
  --    ADD CONSTRAINT FOREIGN KEY (AGG_WORKSHEET_ID)
  --       REFERENCES AGG_WORKSHEET (AGG_WORKSHEET_ID);
--ALTER TABLE FINAL_REVIEW
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

  --ALTER TABLE AGG_RESPONSE
  --    ADD CONSTRAINT FOREIGN KEY (SUBJECTIVE_RESP_ID)
  --       REFERENCES SUBJECTIVE_RESP (SUBJECTIVE_RESP_ID);
ALTER TABLE AGG_RESPONSE
    ADD CONSTRAINT FOREIGN KEY (AGG_RESP_STAT_ID)
       REFERENCES AGG_RESP_STAT (AGG_RESP_STAT_ID);
  --ALTER TABLE AGG_RESPONSE
  --    ADD CONSTRAINT FOREIGN KEY (AGG_WORKSHEET_ID)
  --       REFERENCES AGG_WORKSHEET (AGG_WORKSHEET_ID);
--ALTER TABLE AGG_RESPONSE
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE SUBJECTIVE_RESP
    ADD CONSTRAINT FOREIGN KEY (RESPONSE_TYPE_ID)
       REFERENCES RESPONSE_TYPE (RESPONSE_TYPE_ID);
  --ALTER TABLE SUBJECTIVE_RESP
  --    ADD CONSTRAINT FOREIGN KEY (QUESTION_ID)
  --       REFERENCES SCORECARD_QUESTION (QUESTION_ID);
--ALTER TABLE SUBJECTIVE_RESP
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE FIX_ITEM
    ADD CONSTRAINT FOREIGN KEY (FINAL_FIX_S_ID)
       REFERENCES FINAL_FIX_STATUS (FINAL_FIX_S_ID);
  --ALTER TABLE FIX_ITEM
  --    ADD CONSTRAINT FOREIGN KEY (AGG_RESPONSE_ID)
  --       REFERENCES AGG_RESPONSE (AGG_RESPONSE_ID);
  --ALTER TABLE FIX_ITEM
  --    ADD CONSTRAINT FOREIGN KEY (FINAL_REVIEW_ID)
  --       REFERENCES FINAL_REVIEW (FINAL_REVIEW_ID);
--ALTER TABLE FIX_ITEM
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

--ALTER TABLE SCORECARD_QUESTION -- DEC(18) CAN'T REFERENCE SERIAL8
--    ADD CONSTRAINT FOREIGN KEY (Q_TEMPLATE_V_ID)
--       REFERENCES QUESTION_TEMPLATE (Q_TEMPLATE_V_ID);
ALTER TABLE SCORECARD_QUESTION
    ADD CONSTRAINT FOREIGN KEY (EVALUATION_ID)
       REFERENCES EVALUATION (EVALUATION_ID);
  --ALTER TABLE SCORECARD_QUESTION
  --    ADD CONSTRAINT FOREIGN KEY (SCORECARD_ID)
  --       REFERENCES SCORECARD (SCORECARD_ID);
--ALTER TABLE SCORECARD_QUESTION
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE QUESTION_TEMPLATE
    ADD CONSTRAINT FOREIGN KEY (PROJECT_TYPE)
       REFERENCES PROJECT_TYPE (PROJECT_TYPE_ID);
ALTER TABLE QUESTION_TEMPLATE
    ADD CONSTRAINT FOREIGN KEY (SECTION_ID)
       REFERENCES SCORECARD_SECTION (SECTION_ID);
--ALTER TABLE QUESTION_TEMPLATE
--    ADD CONSTRAINT FOREIGN KEY (MODIFY_USER)
--       REFERENCES SECURITY_USER (LOGIN_ID);

ALTER TABLE SCORECARD_SECTION
    ADD CONSTRAINT FOREIGN KEY (GROUP_ID)
       REFERENCES SC_SECTION_GROUP (GROUP_ID);

ALTER TABLE EVALUATION
    ADD CONSTRAINT FOREIGN KEY (EVALUATION_TYPE_ID)
       REFERENCES EVALUATION_TYPE (EVALUATION_TYPE_ID);

-- Index creation
--DROP INDEX PROJECT_I1;
--DROP INDEX PROJECT_I2;
--DROP INDEX PHASE_INSTANCE_I1;
--DROP INDEX PHASE_INSTANCE_I2;
--DROP INDEX R_USER_ROLE_I1;
--DROP INDEX R_USER_ROLE_I2;
--DROP INDEX R_USER_ROLE_I3;
--DROP INDEX R_USER_ROLE_I4;
--DROP INDEX PAYMENT_INFO_I1;
--DROP INDEX PAYMENT_INFO_I2;

CREATE INDEX PROJECT_I1 ON PROJECT (CUR_VERSION ASC);
CREATE INDEX PROJECT_I2 ON PROJECT (PROJECT_ID ASC);
CREATE INDEX PHASE_INSTANCE_I1 ON PHASE_INSTANCE (CUR_VERSION ASC);
CREATE INDEX PHASE_INSTANCE_I2 ON PHASE_INSTANCE (PHASE_INSTANCE_ID ASC);
CREATE INDEX R_USER_ROLE_I1 ON R_USER_ROLE (CUR_VERSION ASC);
CREATE INDEX R_USER_ROLE_I2 ON R_USER_ROLE (R_USER_ROLE_ID ASC);
CREATE INDEX R_USER_ROLE_I3 ON R_USER_ROLE (LOGIN_ID ASC);
CREATE INDEX R_USER_ROLE_I4 ON R_USER_ROLE (PROJECT_ID ASC);
CREATE INDEX PAYMENT_INFO_I1 ON PAYMENT_INFO (CUR_VERSION ASC);
CREATE INDEX PAYMENT_INFO_I2 ON PAYMENT_INFO (PAYMENT_INFO_ID ASC);


CREATE INDEX SUBMISSION_I1 ON SUBMISSION (CUR_VERSION ASC);
CREATE INDEX SUBMISSION_I2 ON SUBMISSION (SUBMISSION_ID ASC);
CREATE INDEX SUBMISSION_I3 ON SUBMISSION (PROJECT_ID ASC);
CREATE INDEX SUBMISSION_I4 ON SUBMISSION (SUBMISSION_TYPE ASC);
CREATE INDEX SUBMISSION_I5 ON SUBMISSION (IS_REMOVED ASC);

--CREATE INDEX FIXITEM_I1 ON FIX_ITEM (CUR_VERSION ASC);
--CREATE INDEX FIXITEM_I2 ON SUBMISSION (FIX_ITEM_ID ASC);

-- agg_response, existing indexes: agg_resp_stat_id, agg_response_id
-- subjective_resp, existing indexes: (question_id,cur_version), response_type_id
CREATE INDEX SUBJECTIVE_RESP_I1 ON SUBJECTIVE_RESP (SUBJECTIVE_RESP_ID ASC);
-- scorecard_question, existing indexes: scorecard_id, question_id, q_template_v_id, evaluation_id
-- testcase_question, existing indexes: question_id


-- ProjectTracker "constants"
INSERT INTO REVIEW_ROLE VALUES (1, 'Designer/Developer');
INSERT INTO REVIEW_ROLE VALUES (2, 'Primary Screener');
INSERT INTO REVIEW_ROLE VALUES (3, 'Reviewer');
INSERT INTO REVIEW_ROLE VALUES (4, 'Aggregator');
INSERT INTO REVIEW_ROLE VALUES (5, 'Final Reviewer');
INSERT INTO REVIEW_ROLE VALUES (6, 'Product Manager');
INSERT INTO REVIEW_ROLE VALUES (7, 'Removed');

INSERT INTO REVIEW_PHASE VALUES (1, 'Submission');
INSERT INTO REVIEW_PHASE VALUES (2, 'Screening');
INSERT INTO REVIEW_PHASE VALUES (3, 'Review');
INSERT INTO REVIEW_PHASE VALUES (4, 'Aggregation');
INSERT INTO REVIEW_PHASE VALUES (5, 'Aggregation Review');
INSERT INTO REVIEW_PHASE VALUES (6, 'Final Fixes');
INSERT INTO REVIEW_PHASE VALUES (7, 'Final Review');
INSERT INTO REVIEW_PHASE VALUES (8, 'Component Preparation');

INSERT INTO PAYMENT_STATUS VALUES (1, 'Not Paid');
INSERT INTO PAYMENT_STATUS VALUES (2, 'Payment Sent');

INSERT INTO REVIEW_RESP VALUES (1, 'Stress');
INSERT INTO REVIEW_RESP VALUES (2, 'Failure');
INSERT INTO REVIEW_RESP VALUES (3, 'Accuracy');

INSERT INTO PROJECT_TYPE VALUES (1, 'Design');
INSERT INTO PROJECT_TYPE VALUES (2, 'Development');

INSERT INTO PROJECT_STATUS VALUES (1, 'In Progress');
INSERT INTO PROJECT_STATUS VALUES (2, 'Terminated');
INSERT INTO PROJECT_STATUS VALUES (3, 'Pending Start');
INSERT INTO PROJECT_STATUS VALUES (4, 'Completed');

-- DocumentManager "constants"

--    Q_TEMPLATE_V_ID    SERIAL8 NOT NULL,
--    Q_TEMPLATE_ID      DEC(18) NOT NULL,
--    PROJECT_TYPE       DEC(18) NOT NULL,
--    SCORECARD_TYPE     DEC(7) NOT NULL,
--    QUESTION_TEXT      LVARCHAR NOT NULL,
--    QUESTION_WEIGHT    DEC(7) NOT NULL,
--    QUESTION_SEQ_LOC   DEC(7) NOT NULL,
--    SECTION_ID         DEC(18) NOT NULL,
--    QUESTION_TYPE      DEC(7) NOT NULL,
--    MODIFY_DATE        DATETIME YEAR TO FRACTION(3)
--                       DEFAULT CURRENT YEAR TO FRACTION(3) NOT NULL,
--    MODIFY_USER        DEC(18) NOT NULL,
--    CUR_VERSION        DEC(1) NOT NULL

--INSERT INTO QUESTION_TEMPLATE VALUES (1, 1, 1, 1,
--    'Diagrams exist in a .zargo file that can be opened using Poseidon.',
--    4, 1, 1, 1, CURRENT YEAR TO FRACTION(3), 296466, 1);

--INSERT INTO QUESTION_TEMPLATE VALUES (2, 2, 1, 1,
--    'Provides a descriptive overview of class usage in the Documentation tab of Poseidon',
--    4, 1, 2, 2, CURRENT YEAR TO FRACTION(3), 296466, 1);
--INSERT INTO QUESTION_TEMPLATE VALUES (3, 3, 1, 1,
--    'Where applicable sub-packages have been created to separate functionality.',
--    4, 2, 2, 2, CURRENT YEAR TO FRACTION(3), 296466, 1);

--INSERT INTO QUESTION_TEMPLATE VALUES (4, 4, 1, 1,
--    'Variable scope is correctly defined (i.e. the variables are well encapsulated.)',
--    4, 1, 3, 2, CURRENT YEAR TO FRACTION(3), 296466, 1);

--INSERT INTO SC_SECTION_GROUP VALUES (1, 'Minimum Requirements Checklist', 1);
--INSERT INTO SCORECARD_SECTION VALUES (1, 'Minimum Requirements Checklist', 4, 1, 1);

--INSERT INTO SC_SECTION_GROUP VALUES (2, 'Class Diagram', 2);
--INSERT INTO SCORECARD_SECTION VALUES (2, 'Class Definition', 4, 1, 2);
--INSERT INTO SCORECARD_SECTION VALUES (3, 'Variable Definition', 4, 2, 2);


INSERT INTO AGG_APPROVAL VALUES (1, 'Approved');
INSERT INTO AGG_APPROVAL VALUES (2, 'Rejected');

INSERT INTO AGG_RESP_STAT VALUES (1, 'Accepted');
INSERT INTO AGG_RESP_STAT VALUES (2, 'Rejected');
INSERT INTO AGG_RESP_STAT VALUES (3, 'Duplicate');

INSERT INTO EVALUATION_TYPE VALUES (1, 'Subjective Evaluation');
INSERT INTO EVALUATION_TYPE VALUES (2, 'Objective Evaluation');

INSERT INTO EVALUATION VALUES (1, 'Strongly Disagree', 1, 1);
INSERT INTO EVALUATION VALUES (2, 'Somewhat Agree', 2, 1);
INSERT INTO EVALUATION VALUES (3, 'Agree', 3, 1);
INSERT INTO EVALUATION VALUES (4, 'Strongly Agree', 4, 1);
INSERT INTO EVALUATION VALUES (5, 'Yes', 1, 2);
INSERT INTO EVALUATION VALUES (6, 'No', 0, 2);

INSERT INTO FINAL_FIX_STATUS VALUES (1, 'Not Fixed');
INSERT INTO FINAL_FIX_STATUS VALUES (2, 'Fixed');

INSERT INTO RESPONSE_TYPE VALUES (1, 'Required');
INSERT INTO RESPONSE_TYPE VALUES (2, 'Recommended');
INSERT INTO RESPONSE_TYPE VALUES (3, 'Comment');

INSERT INTO TESTCASE_APPROVAL VALUES (1, 'Approved');
INSERT INTO TESTCASE_APPROVAL VALUES (2, 'Rejected');
