--
-- DO NOT EDIT THIS FILE!!!
--

DELETE FROM submission_image;
DELETE FROM submission_payment;
DELETE FROM submission_review;
DELETE FROM contest_result;
DELETE FROM submission_prize_xref;
DELETE FROM submission;
DELETE FROM contest_document_xref;
DELETE FROM document;
DELETE FROM image;


DELETE FROM path;

DELETE FROM contest_medium_xref;
DELETE FROM contest_registration;
DELETE FROM contest_prize_xref;
DELETE FROM contest_file_type_xref;
DELETE FROM contest_config;
DELETE FROM contest_result;
DELETE FROM contest;

DELETE FROM prize;

DELETE FROM email WHERE user_id = 1;
DELETE FROM common_oltp:user_group_xref WHERE login_id = 1;
DELETE FROM informixoltp:coder WHERE coder_id = 1;
DELETE FROM common_oltp:security_user WHERE login_id = 1;
DELETE FROM common_oltp:user WHERE user_id = 1;

