<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:import href="../top.xsl"/>
  <xsl:import href="../script.xsl"/>
  <xsl:import href="../includes/body_top.xsl"/>  
  <xsl:import href="../foot.xsl"/>
  <xsl:import href="../includes/modules/practice_room.xsl"/>
  <xsl:import href="../includes/modules/calendar.xsl"/>
  <xsl:import href="../includes/modules/tournament_invit02_links.xsl"/>  
  <xsl:import href="../includes/modules/invit02_rule_links.xsl"/> 
  <xsl:import href="../includes/global_left.xsl"/> 
  <xsl:import href="../includes/public_right_col.xsl"/>     
  <xsl:output indent="no" method="html" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN"/>
  <xsl:template match="/">
    <HTML>
      <HEAD>
        <xsl:call-template name="Preload"/>      
        <TITLE>TopCoder :: Tournaments</TITLE>
        <xsl:call-template name="CSS"/>      
        <!--<LINK REL="stylesheet" TYPE="text/css" HREF="/css/style.css"/>
        <LINK REL="stylesheet" TYPE="text/css" HREF="/css/coders.css"/>-->
        <META NAME="description" CONTENT="TopCoder is a programming tournament site. All members who compete attain a rating that provides a metric for coding competence and potential. These ratings, coupled with tournament performance, can lead to monetary rewards and employment opportunities."/>
        <META NAME="keywords" CONTENT="Computer Jobs, Programming, Programming Jobs, Programming Contest, Programming Competition, Online Games, Coding, Information Technology Jobs, Java, C++"/>
      </HEAD>
      <BODY BGCOLOR="#CCCCCC" TOPMARGIN="0" MARGINHEIGHT="0" LEFTMARGIN="0" MARGINWIDTH="0">
        <a name="top_page"></a>
        <xsl:variable name="contestId">
          <xsl:value-of select="/TC/SCHEDULE/ContestId"/>
        </xsl:variable>
        <xsl:call-template name="Top"/>
        <!-- Body Begins -->
        <TABLE WIDTH="100%" HEIGHT="69%" BORDER="0" CELLPADDING="0" CELLSPACING="0" BGCOLOR="#CCCCCC">
          <TR>
            <!-- Left Column Begins -->
            <TD WIDTH="180" VALIGN="top">
              <!-- Left Column Include Begins -->  
              <!-- Global Seconday Nav Begins -->  
              <xsl:call-template name="global_left"/>
              <!-- Global Seconday Nav Ends -->      
              <!-- Left Column Include Ends -->          
            </TD>
            <!-- Left Column Ends -->
            <!-- Gutter Begins -->
            <TD WIDTH="4" BGCOLOR="#CCCCCC" VALIGN="top"><IMG SRC="/i/clear.gif" WIDTH="4" HEIGHT="26" BORDER="0"/></TD>
            <!-- Gutter Ends -->
            <!-- Body Area -->
            <!-- Center Column Begins -->  
		<TD CLASS="bodyText" WIDTH="100%" BGCOLOR="#CCCCCC" VALIGN="top">
<xsl:call-template name="BodyTop">
  <xsl:with-param name="image1">steelblue</xsl:with-param>
  <xsl:with-param name="image">tournaments_blue</xsl:with-param>
  <xsl:with-param name="title">&#160;</xsl:with-param>
</xsl:call-template>
<TABLE BORDER="0" CELLSPACING="0" CELLPADDING="0" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%">
	<TR>
		<TD BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" VALIGN="top" WIDTH="11"><IMG SRC="/i/clear.gif" ALT="" WIDTH="11" HEIGHT="1" BORDER="0"/></TD>
		<TD COLSPAN="2" VALIGN="top" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%" CLASS="statText"><IMG SRC="/i/clear.gif" ALT="" WIDTH="240" HEIGHT="1" BORDER="0"/><BR/>
    <!-- Coder of the Week Pulldown Begins -->		
    <xsl:call-template name="tournament_invit02_links"/>
    <BR/>			
        <xsl:call-template name="invit02_rule_links"/>
	<!-- Coder of the Week Pulldown Ends -->

					<TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
                    <TR>
                      <TD COLSPAN="4" VALIGN="middle" HEIGHT="18" CLASS="statTextBig" BACKGROUND="/i/steel_gray_bg.gif">&#160;&#160;qubits Breakdown</TD>
                    </TR>
						<!-- <TR>
							<TD WIDTH="15%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/orangebv_bg.gif">Round #1</TD>
							<TD WIDTH="15%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif"><A HREF="/index?t=schedule&amp;c=invit02_rnd2" CLASS="statTextBig"></A>Round #2</TD>
							<TD WIDTH="15%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif"><A HREF="/index?t=schedule&amp;c=invit02_rnd3" CLASS="statTextBig"></A>Round #3</TD>
							<TD WIDTH="15%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif"><A HREF="/index?t=schedule&amp;c=invit02_rnd4" CLASS="statTextBig"></A>Round #4</TD>
							<TD WIDTH="15%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif"><A HREF="/index?t=schedule&amp;c=invit02_semi" CLASS="statTextBig"></A>Semi</TD>	
							<TD WIDTH="25%" ALIGN="center" VALIGN="middle" HEIGHT="16" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif"><A HREF="/index?t=schedule&amp;c=invit02_champ" CLASS="statTextBig"></A>Champ</TD>												
						</TR> -->
                    </TABLE><BR/>         
       <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
       <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Seed</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Handle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Rating</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Vol.</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Avg. Award</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$1,250</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$2,500</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$4,000</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$10,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$15,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$20,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$50,000</B></FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">1</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">SnapDragon</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3151</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">433</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$19400.66</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.36%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">2</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">reid</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3085</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">390</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16971.31</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.9%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">3</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">NDBronson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2988</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">441</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$15971.35</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.30%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.2%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">4</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">John Dethridge</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3079</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">404</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$13958.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.67%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">38.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.31%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">5</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ZorbaTHut</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3132</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">274</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16361.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.631%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.10%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">6</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">radeye</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2732</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$7019.69</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">45.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.21%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.22%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.15%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">7</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dmwright</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2785</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">350</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6486.43</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">42.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.81%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.44%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">8</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">malpt</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2617</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">491</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$5059.46</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">36.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.11%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.45%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.71%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">9</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ambrose</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2693</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">543</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6346.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">30.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">34.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">8.85%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.66%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.29%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">10</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dgarthur</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2501</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4107.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">39.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">20.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.04%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.64%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.967%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">11</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">obfuscator</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2434</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">320</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$3328.17</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">48.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.50%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.582%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.124%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">12</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">DjinnKahn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2576</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">325</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2992.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">54.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.87%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.40%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.711%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.245%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">13</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jms137</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2299</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">285</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1707.68</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">71.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.70%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.267%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.100%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.026%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.004%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">14</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">moira</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2065</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">437</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1965.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">70.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">19.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.79%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.03%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.393%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.085%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.021%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">15</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">lars</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2117</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">629</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$2483.56</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">62.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">21.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.28%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.937%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.399%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.227%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">16</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">kyky</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2070</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">401</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1838.72</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">68.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">23.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.97%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.833%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.151%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.032%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.005%</FONT></TD></TR>
</TABLE>
<BR/>
      <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
<TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Seed</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Handle</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Rating</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Vol.</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">Avg. Award</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$1,250</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$2,500</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">$4,000</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$10,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$15,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$20,000</B></FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff"><B>$50,000</B></FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">1</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">SnapDragon</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3151</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">433</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$19400.66</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.36%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.7%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">8</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">malpt</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2617</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">491</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$5059.46</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">36.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">32.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.11%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.45%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.71%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">9</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ambrose</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2693</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">543</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6346.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">30.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">34.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">8.85%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.16%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.66%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.29%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">16</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">kyky</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2070</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">401</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1838.72</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">68.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">23.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">6.97%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.833%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.151%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.032%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.005%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">2</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">reid</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3085</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">390</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16971.31</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">26.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.9%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">7</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dmwright</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2785</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">350</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$6486.43</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">42.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.44%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.81%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.44%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">10</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">dgarthur</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2501</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">512</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$4107.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">27.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">39.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">20.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.77%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.04%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.64%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.967%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">15</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">lars</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2117</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">629</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$2483.56</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">62.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">21.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">10.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">4.28%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.937%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.399%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.227%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">3</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">NDBronson</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2988</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">441</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$15971.35</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.30%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">15.2%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">6</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">radeye</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2732</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">327</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$7019.69</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.46%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">45.8%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">9.21%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">5.22%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2.15%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">11</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">obfuscator</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2434</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">320</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$3328.17</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">21.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">48.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">23.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.50%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.98%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.582%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.124%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">14</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">moira</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2065</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">437</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">$1965.90</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">70.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">19.5%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">7.79%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">2.03%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.393%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.085%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffff00">.021%</FONT></TD></TR>
<TR></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">4</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">John Dethridge</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3079</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">404</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$13958.76</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.67%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">38.9%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">6.31%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">10.2%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">13.1%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">14.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">5</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">ZorbaTHut</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3132</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">274</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$16361.57</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.631%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">7.08%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">41.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">4.10%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">11.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">18.3%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">17.5%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">12</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">DjinnKahn</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2576</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">325</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$2992.59</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">24.7%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">54.6%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">16.4%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.87%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">1.40%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.711%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.245%</FONT></TD></TR>
  <TR><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ffffff">13</FONT></TD><TD><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">jms137</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">2299</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">285</FONT></TD><TD ALIGN="RIGHT"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">$1707.68</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">71.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">25.0%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">3.70%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.267%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.100%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.026%</FONT></TD><TD ALIGN="CENTER"><FONT SIZE="2" FACE="arial, verdana, helvetica, sans-serif" COLOR="#ff0000">.004%</FONT></TD></TR>
</TABLE>
       
       
	<BR/><IMG SRC="/i/m/qubits_mug.gif" ALT="" WIDTH="55" HEIGHT="61" BORDER="0" HSPACE="6" VSPACE="1" ALIGN="left"/>
By&#160;qubits<BR/><DIV><I>TopCoder Member</I><BR/><A HREF="/stat?c=member_profile&amp;cr=105922"><FONT COLOR="#FFFFFF"> Author Profile</FONT></A></DIV><BR CLEAR="all"/><BR/>
				    <TABLE WIDTH="100%" BORDER="0" CELLPADDING="0" CELLSPACING="1">
                        <TR><TD VALIGN="middle" HEIGHT="18" CLASS="statTextBig" BACKGROUND="/i/steel_bluebv_bg.gif">&#160;&#160;<A HREF="#top" CLASS="statText">Back to top</A></TD></TR>
                    </TABLE>
                    
          <P><BR/></P>
    </TD>
    <TD VALIGN="top" WIDTH="10"><IMG SRC="/i/clear.gif" ALT="" WIDTH="10" HEIGHT="1" BORDER="0"/></TD>
  </TR>
  <TR>
    <TD COLSPAN="4" VALIGN="top" BGCOLOR="#000033" BACKGROUND="/i/steel_darkblue_bg.gif" WIDTH="100%"><IMG SRC="/i/clear.gif" ALT="" WIDTH="1" HEIGHT="10" BORDER="0"/></TD>
  </TR>     
  <TR>
    <TD VALIGN="top" BACKGROUND="" BGCOLOR="#CCCCCC" WIDTH="11" ALIGN="right"><IMG SRC="/i/clear.gif" ALT="" WIDTH="11" HEIGHT="8" BORDER="0"/></TD>
    <TD BACKGROUND="/i/steel_darkblue_bg.gif" VALIGN="top" BGCOLOR="#000033" WIDTH="14"><IMG SRC="/i/table_mid_left2x.gif" ALT="" WIDTH="14" HEIGHT="8" BORDER="0"/></TD>
    <TD BACKGROUND="/i/steel_darkblue_bg.gif" VALIGN="top" BGCOLOR="#000033" WIDTH="100%"><IMG SRC="/i/clear.gif" ALT="" WIDTH="1" HEIGHT="1" BORDER="0"/></TD>
    <TD VALIGN="top" BACKGROUND="" BGCOLOR="#CCCCCC" WIDTH="10"><IMG SRC="/i/clear.gif" ALT="" WIDTH="1" HEIGHT="1" BORDER="0"/></TD>
  </TR>  
  <TR>
    <TD VALIGN="top" BACKGROUND="" WIDTH="11" ALIGN="right" BGCOLOR="#CCCCCC"><IMG SRC="/i/clear.gif" ALT="" WIDTH="11" HEIGHT="8" BORDER="0"/></TD>
    <TD VALIGN="top" BACKGROUND="" BGCOLOR="#CCCCCC" WIDTH="14"><IMG SRC="/i/table_btm_left2.gif" ALT="" WIDTH="14" HEIGHT="8" BORDER="0"/></TD>
    <TD VALIGN="top" BACKGROUND="" BGCOLOR="#CCCCCC" WIDTH="100%"><IMG SRC="/i/clear.gif" ALT="" WIDTH="1" HEIGHT="1" BORDER="0"/></TD>
    <TD VALIGN="top" BACKGROUND="" BGCOLOR="#CCCCCC" WIDTH="10"><IMG SRC="/i/clear.gif" ALT="" WIDTH="1" HEIGHT="1" BORDER="0"/></TD>
  </TR>
      </TABLE>
    </TD>
  <!-- Center Column Ends -->
<!-- Body Area Ends -->
            <!-- Gutter -->
            <TD WIDTH="4" BGCOLOR="#CCCCCC"><IMG SRC="/i/clear.gif" WIDTH="4" HEIGHT="1" BORDER="0"/></TD>
            <!-- Gutter Ends -->
            <!-- Right Column Begins -->
            <TD WIDTH="180" VALIGN="top"><IMG SRC="/i/clear.gif" WIDTH="170" HEIGHT="1" BORDER="0"/><BR/>
              <!-- Right Column Include Begins --> 
              <xsl:call-template name="public_right_col"/>       
              <!-- Right Column Include Ends -->        
            </TD>
            <!-- Right Column Ends -->
            <!-- Gutter -->
            <TD WIDTH="25" BGCOLOR="#CCCCCC"><IMG SRC="/i/clear.gif" WIDTH="25" HEIGHT="1" BORDER="0"/></TD>
            <!-- Gutter Ends -->
          </TR>
        </TABLE>
        <!-- Body Ends -->
        <xsl:call-template name="Foot"/>
      </BODY>
    </HTML>
  </xsl:template>
</xsl:stylesheet>

