insert into command_query_xref values(1, 1, 1);
insert into command_query_xref values(1, 2, 2);
insert into command_query_xref values(1, 39, 3);
insert into command_query_xref values(1, 45, 4);
insert into command_query_xref values(2, 2, 1);
insert into command_query_xref values(2, 3, 2);
insert into command_query_xref values(2, 4, 3);
insert into command_query_xref values(3, 35, 1);
insert into command_query_xref values(3, 2, 2);
insert into command_query_xref values(3, 45, 3);
insert into command_query_xref values(4, 12, 1);
insert into command_query_xref values(5, 33, 1);
insert into command_query_xref values(5, 6, 2);
insert into command_query_xref values(5, 9, 3);
insert into command_query_xref values(5, 10, 4);
insert into command_query_xref values(5, 11, 5);
insert into command_query_xref values(5, 13, 6);
insert into command_query_xref values(6, 14, 1);
insert into command_query_xref values(6, 15, 2);
insert into command_query_xref values(6, 31, 3);
insert into command_query_xref values(6, 41, 4);
insert into command_query_xref values(7, 16, 1);
insert into command_query_xref values(8, 17, 1);
insert into command_query_xref values(9, 18, 1);
insert into command_query_xref values(10, 19, 1);
insert into command_query_xref values(11, 20, 1);
insert into command_query_xref values(12, 21, 1);
insert into command_query_xref values(13, 22, 1);
insert into command_query_xref values(14, 23, 1);
insert into command_query_xref values(15, 24, 1);
insert into command_query_xref values(15, 30, 2);
insert into command_query_xref values(16, 25, 1);
insert into command_query_xref values(16, 30, 2);
insert into command_query_xref values(17, 2, 1);
insert into command_query_xref values(17, 28, 2);
insert into command_query_xref values(17, 29, 3);
insert into command_query_xref values(17, 44, 4);
insert into command_query_xref values(17, 7, 5);
insert into command_query_xref values(17, 8, 6);
insert into command_query_xref values(18, 5, 1);
insert into command_query_xref values(19, 32, 1);
insert into command_query_xref values(20, 36, 1);
insert into command_query_xref values(20, 26, 2);
insert into command_query_xref values(20, 40, 3);
insert into command_query_xref values(20, 45, 4);
insert into command_query_xref values(21, 37, 1);
insert into command_query_xref values(21, 26, 2);
insert into command_query_xref values(21, 45, 3);
insert into command_query_xref values(22, 46, 1);

insert into input_lu values(1, "rd", 1001, "Round ID");
insert into input_lu values(2, "rm", 1001, "Room ID");
insert into input_lu values(3, "cr", 1001, "Coder ID");
insert into input_lu values(4, "pm", 1001, "Problem ID");
insert into input_lu values(5, "sd", 1003, "Start date");
insert into input_lu values(6, "ed", 1003, "End date");
insert into input_lu values(7, "nr", 1001, "Number of records");
insert into input_lu values(8, "sr", 1001, "Start rank");
insert into input_lu values(9, "er", 1001, "End rank");
insert into input_lu values(10, "ct", 1001, "Contest ID");
insert into input_lu values(11, "dn", 1001, "Division ID");
insert into input_lu values(12, "br", 1001, "Base room ID");
insert into input_lu values(13, "sm", 1001, "Start room");
insert into input_lu values(14, "em", 1001, "End room");
insert into input_lu values(15, "sc", 1001, "Sort column");
insert into input_lu values(16, "sd", 1004, "Sort direction");
insert into input_lu values(17, "cu", 1001, "Current User ID");

insert into query_input_xref values(1, "Y", "$26", 1, 1);
insert into query_input_xref values(1, "Y", "1", 11, 2);
insert into query_input_xref values(1, "Y", "$34", 12, 3);
insert into query_input_xref values(1, "Y", "1", 13, 4);
insert into query_input_xref values(1, "Y", "20", 14, 5);
insert into query_input_xref values(3, "Y", "$26", 1, 1);
insert into query_input_xref values(4, "Y", "$26", 1, 1);
insert into query_input_xref values(4, "Y", "$27", 2, 2);
insert into query_input_xref values(5, "Y", "1", 8, 1);
insert into query_input_xref values(5, "Y", "50", 9, 2);
insert into query_input_xref values(6, "N", null, 1, 1);
insert into query_input_xref values(6, "N", null, 3, 2);
insert into query_input_xref values(7, "N", null, 3, 1);
insert into query_input_xref values(7, "Y", "$42", 1, 2);
insert into query_input_xref values(8, "N", null, 3, 1);
insert into query_input_xref values(8, "Y", "$42", 1, 2);
insert into query_input_xref values(9, "N", null, 3, 1);
insert into query_input_xref values(9, "N", null, 1, 2);
insert into query_input_xref values(9, "N", null, 4, 3);
insert into query_input_xref values(10, "N", null, 3, 1);
insert into query_input_xref values(10, "N", null, 1, 2);
insert into query_input_xref values(10, "N", null, 4, 3);
insert into query_input_xref values(11, "N", null, 3, 1);
insert into query_input_xref values(11, "N", null, 1, 2);
insert into query_input_xref values(11, "N", null, 4, 3);
insert into query_input_xref values(12, "N", null, 4, 1);
insert into query_input_xref values(12, "N", null, 1, 2);
insert into query_input_xref values(13, "N", null, 1, 1);
insert into query_input_xref values(13, "N", null, 3, 2);
insert into query_input_xref values(13, "N", null, 4, 3);
insert into query_input_xref values(14, "N", null, 3, 1);
insert into query_input_xref values(14, "Y", "0", 17, 2);
insert into query_input_xref values(15, "N", null, 3, 1);
insert into query_input_xref values(16, "Y", "10", 7, 2);
insert into query_input_xref values(17, "Y", "1", 8, 1);
insert into query_input_xref values(17, "Y", "10", 9, 2);
insert into query_input_xref values(18, "Y", "1", 8, 1);
insert into query_input_xref values(18, "Y", "10", 9, 2);
insert into query_input_xref values(18, "Y", "1", 11, 3);
insert into query_input_xref values(19, "Y", "1", 8, 1);
insert into query_input_xref values(19, "Y", "10", 9, 2);
insert into query_input_xref values(19, "Y", "1", 11, 3);
insert into query_input_xref values(20, "Y", "1", 8, 1);
insert into query_input_xref values(20, "Y", "25", 9, 2);
insert into query_input_xref values(21, "Y", "1", 8, 1);
insert into query_input_xref values(21, "Y", "25", 9, 2);
insert into query_input_xref values(22, "Y", "1", 8, 1);
insert into query_input_xref values(22, "Y", "10", 9, 2);
insert into query_input_xref values(22, "Y", "1", 11, 3);
insert into query_input_xref values(23, "Y", "1", 8, 1);
insert into query_input_xref values(23, "Y", "25", 9, 2);
insert into query_input_xref values(24, "N", null, 3, 1);
insert into query_input_xref values(24, "Y", "1", 8, 2);
insert into query_input_xref values(24, "Y", "50", 9, 3);
insert into query_input_xref values(24, "Y", "3", 15, 4);
insert into query_input_xref values(24, "Y", "ASC", 16, 5);
insert into query_input_xref values(25, "N", null, 3, 1);
insert into query_input_xref values(25, "Y", "1", 8, 2);
insert into query_input_xref values(25, "Y", "50", 9, 3);
insert into query_input_xref values(25, "Y", "3", 15, 4);
insert into query_input_xref values(25, "Y", "ASC", 16, 5);
insert into query_input_xref values(28, "Y", "$42", 1, 1);
insert into query_input_xref values(29, "Y", "$42", 1, 1);
insert into query_input_xref values(29, "Y", "$43", 2, 2);
insert into query_input_xref values(30, "N", null, 3, 1);
insert into query_input_xref values(31, "N", null, 3, 1);
insert into query_input_xref values(32, "Y", "1", 11, 1);
insert into query_input_xref values(32, "Y", "1", 8, 2);
insert into query_input_xref values(32, "Y", "10", 9, 3);
insert into query_input_xref values(33, "N", null, 1, 1);
insert into query_input_xref values(33, "N", null, 2, 2);
insert into query_input_xref values(33, "N", null, 3, 3);
insert into query_input_xref values(35, "N", null, 1, 1);
insert into query_input_xref values(35, "Y", "1", 11, 2);
insert into query_input_xref values(35, "N", null, 15, 3);
insert into query_input_xref values(35, "Y", "ASC", 16, 4);
insert into query_input_xref values(35, "Y", "1", 8, 5);
insert into query_input_xref values(35, "Y", "50", 9, 6);
insert into query_input_xref values(36, "Y", "1", 11, 1);
insert into query_input_xref values(36, "Y", "$38", 12, 2);
insert into query_input_xref values(36, "Y", "1", 13, 3);
insert into query_input_xref values(36, "Y", "20", 14, 4);
insert into query_input_xref values(37, "Y", "1", 11, 1);
insert into query_input_xref values(37, "N", null, 15, 2);
insert into query_input_xref values(37, "Y", "ASC", 16, 3);
insert into query_input_xref values(37, "Y", "1", 8, 4);
insert into query_input_xref values(37, "Y", "50", 9, 5);
insert into query_input_xref values(39, "Y", "$26", 1, 1);
insert into query_input_xref values(39, "N", null, 11, 2);
insert into query_input_xref values(40, "N", null, 11, 1);
insert into query_input_xref values(41, "Y", -666, 17, 1);
insert into query_input_xref values(44, "N", null, 3, 1);
insert into query_input_xref values(44, "Y", "$42", 1, 2);
insert into query_input_xref values(45, "Y", "$26", 1, 1);
insert into query_input_xref values(46, "N", null, 3, 1);

