<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
        
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title>TopCoder Member Video Competition Official Contest Rules</title>

<!-- Meta Tags -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- External CSS -->
<link rel="stylesheet" href="/css/tco09/tco09.css" media="all" type="text/css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" media="screen" href="/css/tc09/screen-ie6.css" />
<![endif]-->

<!-- External JavaScripts -->
<!--[if lt IE 7]>
<script src="http://ie7-js.googlecode.com/svn/version/2.0(beta3)/IE7.js" type="text/javascript"></script>
<![endif]-->
<script type="text/javascript" src="/js/tco09/jquery-1.2.6.js"></script>
<script type="text/javascript" src="/js/tco09/jquery.backgroundPosition.js"></script>
<script type="text/javascript" src="/js/tco09/scripts.js"></script>
<script type="text/javascript" src="/js/tco09/popup.js" ></script>
</head>

<body id="page">
	<div id="teaser">
	<div id="wrapper">
		<div id="wrapperPopup">
			<div id="wrapperContent">
				
				<div id="wrapperContentPopup">
				
								<div id="contentInnerPopup">
                                
                                	<div id="contentPopup">
								
									  <h2>TopCoder Member Video Competition Official Contest Rules</h2>
											<p><strong>ELIGIBILITY.</strong>  The TopCoder, Inc. (&quot;TopCoder&quot;) Member Video Competition is a Contest (the &quot;Contest&quot;) open to individual, registered members of the TopCoder website (and who have agreed and accepted its Terms of Use), who are at least 18 years old and who are lawful residents of the 50 U.S. states, the District of Columbia or Canada (excluding Quebec) and can speak, read and understand English (&quot;Contestant&quot;).  The Contest is also open to English-speaking persons, at least 18 years old (or the age of majority in jurisdictions where the age of majority is over 18 years and where such Contest is legal), and resident in a non-U.S.-embargoed country.  An individual is not eligible for the Contest if he or she is on a Specially Designated Nationals list promulgated and amended, from time to time, by the Office of Foreign Assets Control of United States Department of the Treasury. Contestants must further abide by the TopCoder website <a href="http://topcoderblogs.com/direct/?page_id=24">Terms of Use.</a>  Violation of the TopCoder Terms of Use may result in disqualification from the Contest.  The Contest may only be entered from and in eligible jurisdictions. </p>
											<p><strong>CONTEST PERIOD.</strong>  The Contest begins at 12:00:01 a.m. U.S. Eastern Standard Time (&quot;US EST&quot;) on January 5, 2009 and ends at 11:59:59 p.m. U.S. EST on May 1, 2009.  Winners will be announced prior to or at the 2009 TopCoder Open on June 1, 2009. <strong>ALL ENTRIES MUST BE SUBMITTED DURING THE CONTEST PERIOD.</strong>  Entries submitted before or after Contest Period will not be considered or judged.  Participation constitutes entrant's full and unconditional agreement to and acceptance of these Official Rules. All federal, state, and local laws and regulations apply.</p>
											<p><strong>CONTEST DESCRIPTION.</strong>  The Contest is designed to develop a video that is made up of member submissions.  Videos submitted may be used and put on display at the Onsite Finals of the TCO09. </p>
											<p>The first 100 members to submit a valid and viewable video that meet the submission guidelines below will win a TopCoder T-shirt.  All videos also must include the following information to be accepted: Member handle, Member full name, and Member country. Though English is preferred, any language is acceptable. Members may only submit one video per person.</p>
											<p>TopCoder member must be in good standing to be applicable to win t-shirt. Any and all applicable taxes on prizes are the sole responsibility of the prizewinner.  By submitting your video, you agree that TopCoder may use the video for any promotional use, including, but not limited to, the TCO09, and on the TopCoder web site.  See the &quot;Ownership and Rights&quot; section below.</p>
											<p>HOW TO ENTER:<br /> 
									  			All videos must include the following information to be valid: Member handle, Member full name, and Member country. Though English is preferred, any language is acceptable. Members may only submit one video per person.</p>
											<p>To submit your video, become a member of the TopCoder group here: <a href="http://www.youtube.com/groups_members?name=TCO09.">http://www.youtube.com/groups_members?name=TCO09.</a>  Once you are a member, please upload your video.</p>
                                            <p>SUBMISSION GUIDELINES:<br />
												All videos must include the following information and are limited to approximately 30 seconds:</p>
                                                    <ul>
                                                    	<li>Your handle</li>
                                                    	<li>Your name</li>
                                                    	<li>Your country</li>
                                                    </ul>
                                			<p>All Submissions must be the Contestant's original creation, executed solely by the Contestant, and any credits must be limited to the Contestant's name(s) only. Your Submission may not have been entered in previous contests, nor won previous awards; Nor may your Submission have been previously published or distributed in any media; Your Submission is intended for a family audience and must, in the sole and unfettered discretion of the TopCoder, be suitable for a general audience.  Your Submission must not contain any claims that are not and cannot be substantiated or that would be false and/or misleading to a reasonable consumer.</p>
											<p>The content of the Submission must not be subject to the rights of any third parties, other than TopCoder and/or its licensors. Submissions may not promote third party products or services, or incorporate third party intellectual property, including, but not limited to copyright protected software, images, characters, logos, names and trademarks.  The Submission may not be offensive or otherwise unsuitable for use, as determined in TopCoder's sole discretion. Any submission of robotic, automatic, or programmed entries, or any entries submitted through other unapproved methods are void. </p>
											<p>As a condition of participating in this Contest and by submitting an entry(ies), each Contestant agrees to permit TopCoder to describe, publicize, publish, prepare derivative works including, and link to your Submission for public viewing. By participating in the Contest, you are granting TopCoder: (1) The right include your video in other video compilations created by TopCoder and others; to provide copies of your entered video for use on any media or web site of TopCoder's choosing.  A Contestant may terminate participation in the Contest upon written notice to TopCoder.</p>
											<p><strong>OWNERSHIP AND RIGHTS.</strong>  Contestants retain all ownership rights in their Submissions; provided, however, that as a condition of participation, Competitors hereby grant a perpetual, royalty-free, irrevocable, non-exclusive license to TopCoder to use, reproduce and publish such Submissions or material in connection with the Competition; (b) to publicly display, and/or feature your Submission and all its content in connection with the promotion of this Competition in all media (now known or later developed); and (c) store your Submission on TopCoders' servers, for marketing purposes, and/or for the promotion of the Contest; and (d) to copy, prepare derivative works incorporating, publicly perform, and publicly display, link to, advertise, and promote your video alone or as incorporated with a compilation. You agree to sign any necessary documentation that may be required by TopCoder or its designees to make use of the rights you granted above. You also understand and acknowledge that TopCoder, and/or other Contestants may have developed or commissioned materials similar or identical to your Submission and you waive any claims you may have resulting from any similarities to your Submission.  Nothing in these Rules shall be construed as granting you any right or license under any intellectual property right of TopCoder (including any rights they may have in any patents, copyrights, trademarks, service marks or any trade secrets) or in TopCoder' web site, by implication, estoppel or otherwise, except as expressly set forth herein.</p>
											<p><strong>JUDGING CRITERIA.</strong>   All Submissions, for initial Contest compliance, will be evaluated on by the TopCoder event team for determination, at TopCoder's sole discretion, whether it meets the submission guidelines. </p>
											<p><strong>PRIZES.</strong>  All T-shirts will be sent via the United States Postal Service after the first valid 100 videos are received, though no earlier than March 1, 2009. Unclaimed or undeliverable participatory prizes will be forfeited. Prizes will be mailed to the address provided in the TopCoder Profile as of February 28, 2009. Competitors who do not update their TopCoder Profile with correct mailing information by February 28, 2009 will forfeit their participatory prize. Please allow 6-12 weeks for delivery of your prizes. If your prize is returned, TopCoder will resend your prize to a secondary address provided a request is made by the prizewinning member. TopCoder is not responsible for lost or stolen items and will not send additional prizes due to no receipt.</p>
											<p>No prize substitution is allowed except at the discretion of TopCoder.  Any costs or fees not specifically listed herein are the responsibility of Contest winners.  This Contest is void where prohibited or restricted by law, and subject to applicable federal, state provincial and local laws.</p>
											<p><strong>REQUIREMENTS OF WINNER/PUBLICITY.</strong>  By agreeing to become Contest prize winners, Contestant agrees to the use of his or her name, voice and/or likeness, and entry, for the purpose of advertising, trade, or promotion without further compensation, unless prohibited by law. If a selected Contest prize winners or runner-up cannot be contacted, is ineligible (under these rules or due to a failure to comply with any of the other applicable policies, licenses, rules, and terms of service, fails to claim a prize, or fails to timely return the completed and executed releases/agreements as required), prize may be forfeited and an alternate potential winner and/or runner-up may, at TopCoders' discretion, be selected.</p>
											<p><strong>CONDITIONS.</strong> Contest is subject to these Official Rules. By participating, Contestant agrees: (i) to be bound by these complete Official Rules and the decisions of TopCoder which shall be final and binding; and (ii) to waive any right to claim ambiguity in the Contest or these Official Rules, except where prohibited by law. TopCoder reserves the right to cancel or suspend the Contest, in its sole discretion, should it receive fewer than 20 entries, or due to circumstances beyond its control, including natural disasters. TopCoder may, in its sole discretion, cancel, modify or suspend the Contest should a virus, bug, computer problem, unauthorized intervention or other causes beyond TopCoder's control, corrupt the administration, security or proper play of the Contest. TopCoder may prohibit a Contestant from participating in the Contest or winning a prize if, in its sole discretion, it determines such entrant is attempting to undermine the legitimate operation of the Contest by cheating, deception, or any other unfair playing practices of intending to annoy, abuse, threaten, undermine or harass any other contestants or TopCoder representatives. </p>
											<p>By participating in the Contest, Contestant agrees that under no circumstances, including, but not limited to, negligence, shall TopCoder or its licensors, its and their respective officers, directors, employees, shareholders, agents, successors, and assigns, and all prize providers (the &quot;Released Parties&quot;) be liable for any direct, indirect, incidental, special, or consequential damages arising out participation in the Contest, even if any or all of the Released Parties have been advised of the possibility of such damages. Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, therefore such exclusions may not apply to you. TopCoder, parent companies, affiliates, subsidiaries, licensors, advertising, promotion, and fulfillment agencies, and legal advisors, and prize providers, and the respective employees, officers, directors, shareholders, agents, and representatives of each, are not responsible for and shall not be liable for: (i) any errors in Contest-related materials, or late, lost, delayed, damaged, misdirected, stolen, incomplete, illegible, or unintelligible, notices, releases, forms, affidavits, prizes, or other correspondence; (ii) telephone, electronic, hardware or software program, network, Internet, or computer malfunctions, failures, interruptions or difficulties of any kind; (iii) failed, incomplete, garbled, or delayed computer transmissions; (iv) any condition caused by events beyond the control of TopCoder that may cause the Contest to be disrupted or corrupted; (v) any injuries, losses, or damages of any kind arising in connection with or as a result of the prizes, or acceptance, possession, or use of the prizes, or from participation in the Contest or arising from the entrant's access to and use of the TopCoder web site, including without limitation, personal injury, death, and property damage, and claims based on publicity rights, defamation, or invasion of privacy, to the extent permitted by law; or (vi) any errors in any materials associated with the Contest. TopCoder reserves the right to cancel, suspend and/or modify the Contest if any problem corrupts the administration, security, or operation of the Contest, as determined by TopCoder in its sole discretion. TopCoder reserves the right in its sole discretion to disqualify any Contestant it finds to be tampering with the entry process or the operation of the Contest or to be acting in violation of these Official Rules or in an unsportsmanlike or disruptive manner. Any attempt by any person to undermine the legitimate operation of the Contest may be a violation of criminal and civil law, and, should such an attempt be made, TopCoder reserves the right to seek damages from any such person to the fullest extent permitted by law. TopCoder's failure to enforce any term of these Official Rules shall not constitute a waiver of that provision.</p>
											<p><strong>PRIVACY.</strong> All information is collected in the United States, and the use of any personally identifiable information is subject to the terms of the TopCoder Privacy Statement located at: <a href="http://www.topcoder.com/tc?module=Static&d1=about&d2=privacy">http://www.topcoder.com/tc?module=Static&d1=about&d2=privacy.</a> By entering the Contest, the Contestant acknowledges that TopCoder will collect, process and use the personal data provided by the Contestant in connection with and for the purpose of administering of the Contest. </p>
											<p><strong>DISPUTES.</strong>  The laws of the United States and the State of Connecticut govern this Contest. As a condition of participating in the Contest, entrant agrees that any and all actions or proceedings related to the Contest shall be exclusively brought in Superior Court, State of Connecticut (if under state law), Hartford Judicial District or U.S. District Court in the State of Connecticut (if under Federal law), and the parties agree not to raise in connection therewith, and hereby waive, any defenses based upon the venue, the inconvenience of the forum, the lack of personal jurisdiction, the sufficiency of service of process or the like in any such action or suit brought in the State of Connecticut.</p>
											<p><strong>WINNERS LIST AND OFFICIAL RULES</strong>.  A winners list will be posted on the web site <a href="http://www.topcoder.com">http://www.topcoder.com</a> until 90 days after the end of Contest. To obtain a copy of the winners list or a copy of these Official Rules, send your request along with a stamped, self-addressed envelope to: TopCoder, Inc., Attn: Video Contest, 95 Glastonbury Boulevard, Glastonbury, CT 06033. Requests must be received no more than 90 days after the end of Contest.  If you have any questions regarding these Rules, contact us at <a href="mailto:service@topcoder.com">service@topcoder.com.</a></p>
									  <p>Copyright &copy; 2008, TopCoder, Inc. All rights reserved.</p>
									  <p></p>
										
									</div>
										
								</div><!-- End #contentInnerPopup -->
				
				</div><!-- End #wrapperContentPopup -->
				
			</div>
		</div><!-- End #wrapperInner -->
	</div><!-- End #wrapper -->

</div>
</body>
</html>