CREATE INDEX COMPANY_CONTACT_ID_IDX on COMMON_OLTP:COMPANY ( 
         PRIMARY_CONTACT_ID          ASC
);

CREATE INDEX PHONE_USER_ID_IDX on COMMON_OLTP:PHONE ( 
          USER_ID, PRIMARY          ASC 
); 

CREATE INDEX EMAIL_USER_ID_IDX on COMMON_OLTP:EMAIL ( 
          USER_ID, PRIMARY          ASC
);
