<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template name="public_support_left">
			<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top">			
                <TR>
                    <TD WIDTH="25" BACKGROUND="/i/steel_gray_bg.gif" VALIGN="top" ALIGN="right"><IMG SRC="/i/sub_navbox_top_left.gif" WIDTH="25" HEIGHT="1" BORDER="0"/><BR/><IMG SRC="/i/sub_navbox_btm_left.gif" WIDTH="25" HEIGHT="21" BORDER="0"/></TD>
					<TD WIDTH="100%" VALIGN="top" CLASS="moduleTitle" BACKGROUND="/i/steel_gray_bg.gif">
			            <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top">			
                            <TR><TD COLSPAN="2" WIDTH="140" VALIGN="top" BGCOLOR="#CCCCCC"><IMG SRC="/i/clear.gif" WIDTH="140" HEIGHT="1" BORDER="0"/></TD></TR>                                
                            <TR><TD WIDTH="100%" VALIGN="middle" CLASS="statTextBig" BGCOLOR="#333333">&#160;:: more Support/FAQs </TD><TD WIDTH="5" BGCOLOR="#333333" ALIGN="right"><IMG SRC="/i/sub_nav_title_right.gif" WIDTH="5" HEIGHT="21" BORDER="0"/></TD></TR>
                        </TABLE>                    
                    </TD>
                </TR>
            </TABLE>
 			<TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top" BACKGROUND="/i/steel_gray_bg2.gif" BGCOLOR="#43515E"> 
				<TR><TD COLSPAN="2" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0" VSPACE="2"/></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>             
				<TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=general_faq" CLASS="subNav">General FAQ</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=comp_faq" CLASS="subNav">Competition FAQ</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=form_faq" CLASS="subNav">Forms W-9 &amp; W-8BEN FAQ</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=divisions" CLASS="subNav">Divisions</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=comp_preview" CLASS="subNav">Competition Preview</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=getting_started" CLASS="subNav">Getting Started</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=comp_process" CLASS="subNav">Competition Process</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
			    <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=ratings" CLASS="subNav">Ratings Overview</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
			    <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=editor_info" CLASS="subNav">Editor Information</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
			    <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=software_req" CLASS="subNav">Software Requirements</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
			    <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=rules_qual" CLASS="subNav">Rules &amp; Qualification</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
				<TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=guide" CLASS="subNav">Visual Guide</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
				<TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=charities" CLASS="subNav">Charity Donations</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
<!--                <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=support&amp;c=manual" CLASS="subNav">Download Manual</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>-->
                <TR><TD COLSPAN="2" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0" VSPACE="2"/></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD COLSPAN="3" BACKGROUND="/i/steel_gray_bg.gif" ALIGN="right"><IMG SRC="/i/sub_navbox_btm_right.gif" WIDTH="13" HEIGHT="17" BORDER="0"/></TD></TR>
			</TABLE>
            <IMG SRC="/i/logo_ghosted_bracket.gif" WIDTH="160" HEIGHT="77" BORDER="0" ALT="[ TopCoder ]" VSPACE="10"/>
  </xsl:template>
</xsl:stylesheet>
