<%--
 * Copyright (C) 2004 - 2009 TopCoder Inc., All Rights Reserved.  
 *
 * This JSP shows general rules about the tournament.
 *
 * Author TCSDEVELOPER
 * Version 1.0
 * Since 2009 TopCoder Open Site Integration
--%>
<%@ page contentType="text/html;charset=utf-8" %> 
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
        
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

<title>TCO 09 : Tournament Overview</title>

<!-- Meta Tags -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<!-- External CSS -->
<link rel="stylesheet" href="css/tournaments/tco09.css" media="all" type="text/css" />
<!--[if IE 6]>
<link rel="stylesheet" type="text/css" media="screen" href="css/screen-ie6.css" />
<![endif]-->

<!-- External JavaScripts -->
<script type="text/javascript" src="/js/tournaments/tco09/jquery-1.2.6.js"></script>
<script type="text/javascript" src="/js/tournaments/tco09/jquery.backgroundPosition.js"></script>
<script type="text/javascript" src="/js/tournaments/tco09/scripts.js"></script>
<script type="text/javascript" src="/js/arena.js"></script> 
<style type="text/css">
<!--
.style2 {color: #FF0000}
-->
</style>
</head>

<body id="page">

    <div id="wrapper">
        <div id="wrapperInner">
            <div id="wrapperContent">
                
                <div id="wrapperContentInner">
                
                    <jsp:include page="../../header.jsp"/>
                    
                    <jsp:include page="../../mainNav.jsp" >
                        <jsp:param name="mainTab" value="overview"/>
                    </jsp:include>
                    
                    <div id="content">
                            <div class="contentTopLeft"><div class="contentTopRight">
                                <div class="contentTopInner"></div>
                            </div></div>
                            
                            <div id="contentInner" class="contentInner">
                            
                                <div id="contentInnerInner">

                                    <jsp:include page="../topArea.jsp"/>
                                
                                    <div class="bottomArea">
                                        <div class="bottomLeft"><div class="bottomRight">
                                            
                                            <jsp:include page="../../secondaryNav.jsp" >
                                                <jsp:param name="mainTab" value="overview"/>
                                                <jsp:param name="secondaryTab" value="rules"/>
                                            </jsp:include>

                                            <jsp:include page="../../tertiaryNav.jsp" >
                                                <jsp:param name="mainTab" value="overview"/>
                                                <jsp:param name="secondaryTab" value="rules"/>
                                                <jsp:param name="tertiaryTab" value="tco09"/>
                                            </jsp:include>
                                            
                                            <div class="bottomAreaContent">
                                                
                                                <div class="mainContent">
                                                    <div id="mainContentInner">
                                                        <div>
                                                            <div class="pageContent">
                                                                <h2 class="title">2009 TopCoder Open Rules</h2>
                                                                    <p><strong>Official Rules &amp; Regulations</strong></p>                                                     
                                                                    <p>NO PURCHASE NECESSARY TO ENTER OR WIN, A PURCHASE WILL NOT INCREASE YOUR CHANCE OF WINNING. VOID WHERE PROHIBITED.</p>
                                                                    <p>Your registration and participation in the 2009 TopCoder Open (&quot;Tournament&quot;) being held online and onsite between February 11, 2009 and June 4, 2009 constitutes agreement with these terms and conditions (&quot;Rules&quot; or &quot;Terms and Conditions&quot;) between you and TopCoder, Inc. (&quot;TopCoder&quot;).  The onsite portion of the Tournament will be held at The Mirage in Las Vegas, Nevada, USA between June 1, 2009 and June 4, 2009.</p>
                                                                    <p><strong>About the Competition</strong></p>
                                                                        <div class="subtitle">
                                                                            <h3 class="subtitle">Entering the Tournament</h3>
                                                                                <p>The Tournament is brought to you by TopCoder, Inc. and is designed to showcase the most prestigious members in the TopCoder community. The Tournament consists of several competitions: Algorithm, Architecture, Assembly, Component Design, Component Development, Marathon, Mod Dash, Specification, and Studio Design (each a &quot;Competition&quot;).  The Tournament is open to all TopCoder members who meet the criteria outlined herein and who register for the Tournament (&quot;Competitors&quot;).  Registration for the Tournament automatically registers you for all Competitions.  For more information about the deadlines for participating in and the specific rules for each Competition, please refer to the specific area of these Rules for such Competition. </p>                                                                        
                                                                            <h3 class="subtitle">General Submission Requirements</h3>
                                                                                <p>All Competitors participating in a Competition will see a Submit option. Clicking the Submit link will take the Competitor to a page that will allow the Competitor to upload information about their submission in the Competition (&quot;Submission&quot;).</p>                                                                        
                                                                                <p>The requirements for a Submission will vary depending on the Competition, so please refer to the specific area of these Rules for each Competition before submitting.</p>                                                                        
                                                                                <p>TopCoder reserves the right at any time to disqualify a Submission from a Competition where, acting in good faith, it believes there are reasonable grounds to warrant disqualification, for example, if TopCoder determines that the Submission does not provide the functionality described or required or the Submission appears to be purposely designed to circumvent these Rules or the spirit of the Tournament and/or Competition.</p>                                                                        
                                                                            <h3 class="subtitle">How to participate</h3>
                                                                                <p>In order to determine how to participate in a Competition, please refer to the specific areas of these Rules for such Competition.</p>                                                                        
                                                                            <h3 class="subtitle">Conditions of Participation</h3>
                                                                                <p>Competitors must be registered members of TopCoder, and also register for the Tournament.  By participating in the Tournament and/or a Competition, you agree to be bound by these Rules and to all decisions of TopCoder, which are final, binding and conclusive in all matters. As a condition of participating in this Tournament and/or a Competition and by submitting a Submission, each Competitor agrees to permit TopCoder to describe, publicize, and link to your entry as described further below. </p>                                                                        
                                                                                <p>Competitors must not cheat; all ideas for Submissions must be solely the Competitor's.  Unless otherwise set forth in these Rules, Competitors may not collaborate on a Submission.  </p>                                                                        
                                                                                <p>IN ORDER TO BE ELIGIBLE, YOU WARRANT THAT YOUR SUBMISSION FOR EACH COMPETITION:</p>
                                                                                    <ul>
                                                                                        <li>Does not include or anticipate the inclusion of any unsuitable or offensive content, including nudity, sexually explicit, disparaging, libelous or other inappropriate content.</li>
                                                                                        <li>Does not include or anticipate the inclusion of any content that is in violation of or infringes third party intellectual property rights including, but not limited to copyrights, including music copyrights, trademarks, and rights of publicity.</li>
                                                                                        <li>Has not been entered in previous contests, or won previous awards. </li>
                                                                                        <li>Has not been published or distributed previously in any media.</li>
                                                                                        <li>Is suitable for a general audience;</li>
                                                                                        <li>Does not contain any claims that are not and cannot be substantiated or that would be false and/or misleading to a reasonable consumer.</li>
                                                                                    </ul>  
                                                                                <p>All decisions relating to the viability of Submissions, the ranking of Submissions and all other matters pertaining to the Tournament and each Competition are within the sole discretion of TopCoder or its designee and shall be final and binding in all respects. </p>                                                                      
                                                                                <p>By participating in the Tournament and/or a Competition, a Competitor who wins a prize releases and agrees to hold harmless TopCoder, its affiliates, subsidiaries, sponsors, advertising and promotion agencies, and prize suppliers, and all of their respective directors, officers, employees, representatives and agents, from and against any and all liability for any loss, property damage or damage to person, including without limitation, death and injury, due in whole or in part, directly or indirectly, from or arising out of participation in the Tournament and/or Competition, or participation in any Tournament and/or Competition-related activity, or the receipt, use or misuse of a prize. </p>                                                                      
                                                                                <p>TopCoder reserves the right to limit the participation of any person in the Tournament and/or any Competition, amend or interpret these Rules or official communications governing the Tournament and each Competition or cancel the Tournament or any Competition for any reason with prior notice. Notices for any such amendment, interpretation or cancellation will be deemed to have been given by posting on the TopCoder website and by virtue of a Competitor's continued participation in the Tournament and/or Competition. A Competitor may terminate participation in the Tournament and each Competition upon written notice to TopCoder.</p>                                                                      
                                                                            <h3 class="subtitle">Eligibility</h3>
                                                                                <p>The Tournament and each Competition is open to all members of the TopCoder website, who have agreed to the terms thereof, and who are at least 18 years of age. Competitors must be (i) a U.S. citizen, (ii) a lawful permanent resident of the U.S., (iii) a temporary resident, asylee, refugee of the U.S., or have a lawfully issued work authorization card permitting unrestricted employment in the U.S., or (iv) a non-U.S. resident authorized in the country in which the member resides while participating in the Tournament and each Competition to perform services as an independent contractor; or (v) with respect to the Algorithm Competition, be in the United States under a valid and current visa issued by the United States government which does not prohibit receiving a cash prize.</p>                                                                        
                                                                          <p>A Competitor is not eligible for the Tournament or a Competition if he/she is a resident of the Quebec province of Canada, Iran, Cuba, North Korea, Sudan or Syria. In addition, a Competitor is not eligible for the Tournament or a Competition if the Competitor is on the Specially Designated National list promulgated and amended, from time to time, by the United States Department of the Treasury.</p>                                                                        
                                                                                <p>All Competitors must be registered members of TopCoder, and must have agreed to these Rules prior to and as a condition for registering for the Tournament and participating in a Competition.</p>                                                                        
                                                                                <p>Competitors must abide by the Terms of Use of TopCoder's website at <a href="http://www.topcoder.com">www.topcoder.com</a>. Violation of the Terms of Use may result in disqualification from the Tournament and a Competition, and/or further consequences as determined in TopCoder's sole discretion.</p>                                                                        
                                                                          <p>Current employees of TopCoder and any Sponsor and those involved in the development, production (including prize suppliers and sponsors), implementation and distribution of the Tournament or a Competition and their advertising or promotion agencies, parent companies, service providers, agents, officers, subsidiaries or affiliates, or any other persons or entities directly associated with the Tournament and members of their immediate families and/or persons living in the same household as such persons, are ineligible to enter the Tournament or a Competition. </p>                                                                        
                                                                            <h3 class="subtitle">General Information About Prizes</h3>
                                                                                <p>All Prizes are listed and shall be awarded in USD.  All prizes will be awarded in each Competition, provided a qualified number of Submissions are received.  If a Competitor cannot or will not accept a prize, then the prize will be forfeited and may be awarded to the next highest scoring Submission. </p>                                                                        
                                                                                <p>Unless otherwise provided herein, by participating in the Tournament and a Competition, a Competitor acknowledges and agrees that if his/her Submission is selected as a winner, the Competitor will receive a cash award only upon verification of all applicable eligibility requirements.  Cash prizes will be paid out by TopCoder (or its designee) in the US in US dollars no later than 60 days following the conclusion of the Tournament and Competition. Taxes, if any, are the sole responsibility of the winner(s).  Prizes which remain unclaimed or undeliverable for a period of six (6) months will be forfeited.</p>                                                                        
                                                                                <p>As a condition of winning and redeeming a cash prize, Competitors will be required to submit a completed (i) Competitor Questionnaire, (ii) Affidavit of Eligibility and Liability and Publicity Release, unless a notarized copy is already on file with TopCoder (iii) IRS Form W-9 or W-8BEN, as appropriate if one is not already on file with TopCoder, (iv) TopCoder Competition Assignment Agreement, if one is not already on file with TopCoder, (v) Travel form, and (vi) brief video introduction.  In completing the Affidavit of Eligibility and Liability and Publicity Release, a Competitor who wins a cash prize (a) confirms his/her eligibility, (b) represents and warrants that he/she has not cheated, (c) verifies the accuracy of the demographic information submitted to, and contained in, the TopCoder member database, (d) authorizes TopCoder to publicize the results of the Tournament and/or Competition, (e) agrees to sign any applicable forms required by tax authorities, (f) grants TopCoder a license to all information submitted during the Tournament and the Competition, and (g) releases TopCoder from liability arising out of any prize won.  TopCoder requires Competitors to complete the Form W-9 or W-8BEN for tax reporting purposes.  Providing false information in the registration process or in the required forms described in this paragraph will result in a forfeiture of a cash prize.</p>                                                                        
                                                                                <p>If a winning Competitor (i) does not reply to such notification or the notification is undeliverable, (ii) does not return the Affidavit of Eligibility/Liability/Publicity release completed and signed within ten (10) days of date of prize notification, or (iii) is not otherwise in compliance with these Rules or the rules of a Competition, the Competitor will be disqualified and forfeit any prize, and TopCoder may, at our discretion, select and notify another Competitor.</p>                                                                        
                                                                                <p>Participatory prizes and non-cash prizes will be mailed within one month following the conclusion of the Tournament and/or Competition via the United States Postal Service to the address provided by the Competitor in their TopCoder profile as of April 27, 2009. Unclaimed or undeliverable participatory prizes will be forfeited. Competitors who do not submit the required information by the applicable deadlines forfeit their prizes.  Please allow 6-12 weeks for delivery. If your prize is returned, TopCoder will resend your prize to a secondary address provided a request is made by the prizewinning Competitor. TopCoder is not responsible for lost or stolen items and will not send additional prizes in the event a prize is not received. </p>                                                                        
                                                                                <p>Each Competitor is eligible to receive only one (1) limited edition 2009 TopCoder Open T-shirt during the Tournament.</p> 
                                                                            <h3 class="subtitle">License to Submissions</h3>
                                                                                <p>As a condition of participation, Competitors hereby grant a perpetual, royalty-free, irrevocable, non-exclusive license to TopCoder (a) to use, reproduce and publish Submissions or material in connection with the Tournament or Competition; (b) to publicly display, and/or feature your Submission and all its content in connection with the promotion of the Tournament or the Competition in all media (now known or later developed); and (c) store your Submission on TopCoder's servers, for marketing purposes, and/or for the promotion of the Tournament or the Competition. You agree to sign any necessary documentation that may be required by TopCoder or its designees to make use of the rights you granted above. You also understand and acknowledge that TopCoder, any Tournament or Competition sponsor(s), and/or other Competitors may have developed or commissioned materials similar or identical to your Submission and you waive any claims you may have resulting from any similarities to your Submission.</p>
                                                                                <p>Nothing in these Rules shall be construed as granting you any right or license under any intellectual property right of TopCoder or any Competition sponsor(s) (including any rights they may have in any patents, copyrights, trademarks, service marks or any trade secrets) or in TopCoder's web site, by implication, estoppel or otherwise, except as may be expressly set forth herein.</p>
                                                                        </div>
                                                                    <p><strong>Travel</strong></p>
                                                                        <div class="subtitle">
                                                                            <h3 class="subtitle">Confirmation</h3>
                                                                                <p>All Competitors who have advanced or won a trip to the onsite portion of the Tournament (&quot;Onsite Competitors&quot;) must arrive at The Mirage no later than 5:00 p.m. PDT (UTC/GMT -7) on Monday, June 1, 2009.  All Onsite Competitors must confirm their attendance at the onsite event no later than 5:00 p.m. EDT (UTC/GMT -4) on April 27, 2009.  In order to confirm attendance, Onsite Competitors must have acquired any necessary <a href="http://www.topcoder.com/wiki/display/tc/Getting+your+Visa+and+Getting+it+Early">travel visas.</a> and confirm their ability to travel to the United States no later than April 27, 2009. If an Onsite Competitor is required to travel from outside the United States, the Onsite Competitor must show proof of a visa and/or passport by 5:00 p.m. EDT (UTC/GMT -4) on April 27, 2009. Onsite Competitors may email a copy of their documents to <a href="mailto: jford@topcoder.com">Jessie D'Amato Ford.</a> Onsite Competitors who fail to meet this requirement may be replaced as an Onsite Competitor.</p>
                                                                          <p>Competitors who are otherwise eligible to compete in any or all of the Competitions will be permitted to participate in the online portions of any/all of them. However, in the event a Competitor advances to the onsite finals in more than one Competition and any of the times for the onsite rounds of the Competitions overlap, the Onsite Competitor may participate in either, but not both, Competition.  The Onsite Competitor must notify TopCoder of the Competition in which s/he will participate as an Onsite Competitor no later than April 27, 2009. </p>
                                                                            <h3 class="subtitle">Visa Assistance</h3>
                                                                                <p>TopCoder will issue visa invitation letters (upon request) to international Competitors who require one to obtain a travel visa to enter the United States. All Competitors that have passed screening for at least one online Competition will receive a visa invitation letter request form.  Competitors must fill out the form in its entirety before a visa letter will be mailed.  Competitors have until 5:00 p.m. EDT (GMT/UTC -4) on April 15, 2009 to request a letter. Visas can take a significant amount of time to obtain in certain countries, so it is in a Competitor's best interests to request one well before the deadline. The cost of obtaining a visa is the sole responsibility of the Competitor. See more information about <a href="http://www.topcoder.com/wiki/display/tc/Getting+your+Visa+and+Getting+it+Early">travel visas.</a></p>
                                                                          <p>The Tournament involves a large number of visa applications by TopCoder members.  By applying for a visa to attend the Tournament, you understand that TopCoder will cooperate with all requests by consulates, the Department of Homeland Security, and law enforcement in connection with such Competitor's visa, including information about the visa applicants' attendance at the Tournament.  Any abuse of the visa application process or any visa obtained for the Tournament is considered a serious violation of US law and these Rules, subject to discipline by TopCoder.</p>
                                                                            <h3 class="subtitle">Travel Details</h3>
                                                                                <p>TopCoder will provide air travel arrangements for each Onsite Competitor. The flight will be reserved and paid for by TopCoder.  Onsite Competitors will arrive on Monday, June 1, 2009 and depart on June 5, 2009. At TopCoder's sole discretion, TopCoder will pay for each Onsite Competitor's airfare up to $1,500, but reserves the right to make exceptions to the maximum amount based on individual circumstances. If an Onsite Competitor wishes to take a flight other than the one provided by TopCoder and/or wishes to stay at a hotel other than The Mirage, the Onsite Competitor shall be responsible for the entire cost of such deviation from the accommodations and travel arrangements provided by TopCoder. In addition, the Onsite Competitor agrees to reimburse TopCoder for any costs, penalties, fines or fees incurred by TopCoder as a result of such deviation.</p>
                                                                                <p>Ground transportation to and from McCarran International Airport will be provided for each Onsite Competitor by TopCoder, as well as hotel accommodations and certain meals. All other expenses are the responsibility of the Onsite Competitor. TopCoder will not provide travel, lodging accommodations, or visa assistance for any guests of an Onsite Competitor.</p>
                                                                                <p>If an Onsite Competitor is eliminated for cheating after he/she is confirmed as a finalist and travel accommodations have already been made for the Onsite Competitor by TopCoder for the onsite finals, that Onsite Competitor will be responsible for reimbursing TopCoder for the cost of such accommodations. TopCoder reserves the right to withhold any future cash prizes won by the Onsite Competitor until the cost of such accommodations has been fully reimbursed. </p>
                                                                                <p>Onsite Competitors must complete the following items and submit them to TopCoder by 5:00 p.m. EDT on Monday, April 27, 2009 (failure to submit these items will disqualify an Onsite Competitor from advancing to the onsite event):</p>
                                                                                    <ul>
                                                                                        <li>Confirmation of attendance/proof of travel documents - Please email <a href="mailto:jford@topcoder.com?subject=Confirmation of Attendance/Proof of Travel Documents">Jessie D'Amato Ford</a> to confirm your attendance onsite. If you require a passport and/or visa to visit the United States, you must show proof of your documents. </li>
                                                                                      <li>Please <a href="http://www.topcoder.com/tc?module=UserStatic&amp;d1=my_home&amp;d2=submitPhoto">submit a photo,</a> if you have not already done so. </li>
                                                                                        <li>Video - Please upload a video to the <a href="http://www.youtube.com/user/TopCoderOpen2009">TCO09 channel</a> if you have not done so already.  Note the rules for the video stated <a href="http://www.topcoder.com/tc?module=Static&amp;d1=tco09&amp;d2=teaser">here</a>.    Please send the link of your video to <a href="mailto: jford@topcoder.com">Jessie D'Amato Ford.</a></li>
                                                                                      <li>Please ensure the information listed in your TopCoder profile is current.  We may need to mail your plane tickets or contact you via telephone. </li>
                                                                                        <li>Complete the Onsite Competitor Questionnaire - your responses may be published in the program for the Tournament. </li>
                                                                                        <li>Travel form - provide TopCoder with the appropriate travel information for your trip to the onsite event.</li>
                                                                                        <li>Affidavit of Eligibility and Liability and Publicity Release - TopCoder must receive the original copy of a notarized affidavit unless a notarized affidavit is already on file with TopCoder. The document must be postmarked by April 27, 2009, and must be sent in such a manner that it will arrive at TopCoder no later than May 22, 2009.</li>
                                                                                            <ul>
                                                                                                <li>If TopCoder already has a notarized affidavit, tax form, or Assignment Agreement on file for an Onsite Competitor, the Onsite Competitor may affirm such document online. </li>
                                                                                            </ul>
                                                                                        <li>TopCoder Competition Assignment Agreement - TopCoder must receive an executed copy of the Agreement unless an executed Agreement is already on file with TopCoder. The Agreement must be postmarked by April 27, 2009, and must be sent in such a manner that it will arrive at TopCoder no later than May 22, 2009. </li>
                                                                                        <li>Applicable tax forms (unless one is already on file with TopCoder). </li>
                                                                                    </ul>
                                                                            <h3 class="subtitle">Indemnification and Release</h3>
                                                                                <p>By submitting a Submission and/or otherwise participating in forum and newsgroup discussions on TopCoder's customer and developer forums, Competitor agrees to indemnify TopCoder and any parent, subsidiary or affiliated entities, TopCoder's officers and employees, and officers and employees of any parent, subsidiary or affiliated entities and hold them harmless from any and all claims and expenses, including attorney's fees, arising from Competitor's use of TopCoder's website(s) and/or the materials gained from TopCoder's website(s) or directly from TopCoder, including any material (including third party material) that Competitor posts on TopCoder's website(s) or in any news forums and any services or products available through TopCoder's website(s). In addition, Competitor hereby releases TopCoder and any parent, subsidiary or affiliated entities, TopCoder's officers and employees, and officers and employees of any parent, subsidiary or affiliated entities from any and all claims, demands, debts, obligations, damages (actual or consequential), costs, and expenses of any kind or nature whatsoever, whether known or unknown, suspected or unsuspected, disclosed or undisclosed, that Competitor may have against them arising out of or in any way related to such disputes and/or to any services or products available at TopCoder's website(s). Competitor hereby agrees to waive all laws that may limit the efficacy of such releases. </p>
                                                                                <p>By register and/or participating in the Tournament or a Competition the Competitor agrees to release TopCoder and any Competition sponsor(s), and its affiliates and agents, and the officers, employees, affiliates, advertising and promotions agencies, prize suppliers, and all of their employees, officers, directors, shareholder's and agents (collectively, the "Releasees") from any and all liability or any injuries, loss or damage of any kind arising from or in connection with the Tournament or a Competition, the use of any Submission, or the acceptance or use of any prize won, except where prohibited by law.</p>
                                                                                <p>Releasees assume no responsibility for incomplete, misdirected, damaged or illegible entries nor for any delayed Submissions or those not received for whatever reason, including without limitation due to internet or e-mail server failure, telephone, human, or other error or for any technical or other malfunctions that may occur including any injury or damage to Competitor's or any other person's computer relating to or resulting from participation in the Tournament or a Competition or downloading any materials during or for the Tournament or a Competition.</p>
                                                                        </div>
                                                                    <p><strong>DISCLAIMER</strong></p>
                                                                        <p>THE MATERIALS AND SERVICES ON TOPCODER'S WEBSITE(S) ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, TOPCODER DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. TOPCODER DOES NOT WARRANT THAT THE FUNCTIONS CONTAINED IN THE MATERIALS WILL BE UNINTERRUPTED OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT TOPCODER'S WEBSITE(S) OR THE SERVER(S) THAT MAKES TOPCODER'S WEBSITE(S) AVAILABLE OR ANY ADVERTISED OR HYPERLINKED SITE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT TOPCODER'S WEBSITE(S), SERVER(S), ADVERTISED OR HYPERLINKED SITES WILL BE ACCESSIBLE AT ALL TIMES. TOPCODER DOES NOT WARRANT THAT SUCH ERRORS, DEFECTS OR INTERRUPTIONS IN SERVICE WILL NOT AFFECT THE RESULTS OF ITS COMPETITIONS AND SOFTWARE DEVELOPMENT PROCESS, AND TOPCODER DISCLAIMS ANY RESPONSIBILITY FOR REDUCED PERFORMANCE OR INOPERABILTIY IN COMPETITIONS OR IN SOFTWARE DEVELOPMENT DUE TO SUCH PROBLEMS. TOPCODER DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF ITS WEBSITE(S) WITH RESPECT TO CORRECTNESS, ACCURACY, RELIABILITY OR OTHERWISE. YOU ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION. TO THE EXTENT THAT APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. </p>
                                                                        <p>Documents, graphics and other materials appearing at TopCoder's website(s) may include technical inaccuracies, typographical errors, and out-of-date information and use of such documents, graphics or other materials is at Competitor's own risk. </p>
                                                                    <p><strong>LIMITATION OF LIABILITY</strong></p>
                                                                        <p>TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, TOPCODER SHALL NOT BE LIABLE FOR ANY DAMAGES (INCLUDING, BUT NOT LIMITED TO, DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES), INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF WINNINGS, DATA OR OTHER DAMAGE TO ANY OTHER INTANGIBLE PROPERTY, EVEN IF TOPCODER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, RESULTING FROM (i) THE USE OR INABILITY TO USE ITS WEBSITE(S), (ii) THE POSTING OF INFORMATION TO, OR THE RECEIPT OF INFORMATION FROM, ITS WEBSITE(S), (iii) THE DISCLOSURE OF, UNAUTHORIZED ACCESS TO OR ALTERATION OF ANY TRANSMISSION OR DATA, (iv) THE STATEMENTS OR CONDUCT OF ANY THIRD PARTY OR (v) ANY OTHER MATTER RELATING TO TOPCODER.</p>
                                                                    <p><strong>Choice of Law and Forum</strong></p>
                                                                        <p>These Rules are governed by the laws of the State of Connecticut. Competitor hereby agrees to submit to the exclusive jurisdiction of the courts of the State of Connecticut. To the extent that applicable laws have mandatory application to these Rules or give Competitor the right to bring action in any other courts, the above limitations may not apply to such Competitor. Use of TopCoder's website(s) and participation in the Tournament or a Competition is unauthorized in any jurisdiction that does not give full effect to all provisions of these Rules. </p>
                                                                    <p><strong>Severability and Enforceability</strong></p>
                                                                        <p>If any provision or portion of these Rules are held illegal, invalid, or unenforceable, in whole or in part, it shall be modified to the minimum extent necessary to correct any deficiencies or replaced with a provision which is as close as is legally permissible to the provision found invalid or unenforceable and shall not affect the legality, validity or enforceability of any other provisions or portions of these Rules. </p>
                                                                    <p><strong>Privacy</strong></p>
                                                                        <p>All information is collected in the United States, and the use of any personally identifiable information is subject to the terms of the TopCoder Privacy Statement located <a href="http://www.topcoder.com/tc?module=Static&amp;d1=about&amp;d2=privacy">here.</a></p>
                                                              <p>By entering or participating in the Tournament or a Competition, the Competitor acknowledges that TopCoder and any Competition sponsor will collect, process and use the personal data provided by the Competitor in connection with and for the purpose of administering of the Tournament and a Competition, including disclosure of names and other information to third parties (e.g., hotels, travel agencies, consulates, etc...). </p>
                                                                    <p><strong>Termination/Exclusion</strong></p>
                                                                        <p>TopCoder reserves the right, in its sole discretion, to revoke any and all privileges associated with the Tournament and a Competition, and to take any other action it deems appropriate including but not limited to disqualification of a Submission or terminating or suspending a Competitor's use of <a href="http://www.topcoder.com">www.topcoder.com</a> and/or <a href="http://www.software,topcoder.com">www.topcodersoftware.com</a> for no reason or any reason whatsoever, including improper use of its website(s) or failure to comply with these Rules, or the Terms of Use of TopCoder's websites, which are incorporated herein by reference. </p>
                                                              <p>If for any reason the Tournament or a Competition is not capable of running as planned due to infection by computer virus, bugs, tampering, unauthorized intervention, fraud, technical failures, uploads of malicious files or viruses, or any other causes beyond the control of TopCoder which corrupt or affect the administration, security, fairness, integrity, or proper conduct of the Tournament or a Competition, TopCoder reserves the right at its sole discretion, to disqualify any entry or any individual who tampers with the entry or judging process, and to cancel, terminate, modify or suspend the Tournament or a Competition and select winners using all eligible, non-suspect Submissions received as of the date of termination. Releasees assume no responsibility for any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, Submissions.</p>
                                                                        <p>CAUTION: ANY ATTEMPT TO DELIBERATELY DAMAGE ANY WEBSITE OR UNDERMINE THE LEGITIMATE OPERATION OF THE TOURNAMENT OR A COMPETITION IS A VIOLATION OF CRIMINAL AND CIVIL LAWS AND SHOULD SUCH AN ATTEMPT BE MADE, TOPCODER RESERVES THE RIGHT TO SEEK DAMAGES TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
                                                                    <p><strong>Other</strong></p>
                                                                        <p>The Tournament and each Competition is void in whole or in part where prohibited by law. </p>
                                                                        <p>A list of winners by handles for the Tournament and each Competition will be available on the web site at <a href="http://www.topcoder.com">http://www.topcoder.com</a> displayed for at least 3 months after the end of the Tournament and each Competition.</p>
                                                              <p>TopCoder may assign, novate or subcontract any or all of its rights and obligations under these Rules at any time.</p>
                                                                        <p>The Tournament and each Competition is brought to you by TopCoder, Inc., 95 Glastonbury Boulevard, Glastonbury, CT 06033 Telephone: (860) 633-5540</p>
                                                                        <p>If you have any questions regarding these Rules, contact us at <a href="mailto:service@topcoder.com">service@topcoder.com.</a></p>
                                                                        <p>All trademarks, tradenames, and/or tradestyles used in the Tournament and a Competition are the sole property of the respective owners of such trademarks, tradenames, and/or tradestyles and are used herein solely for identification purposes.</p>
                                                            </div>                                                        
                                                        </div>
                                                    </div><!-- End #mainContentInner -->
                                                </div><!-- End #mainContent -->                                                 
                                                
                                                <jsp:include page="../../sponsors.jsp"/>
                                                
                                            </div><!-- End .bottomAreaContent -->
                                        
                                        </div></div>
                                    </div><!-- End .bottomArea -->
                                    
                                </div><!-- End #contentInnerInner -->
                            
                            </div><!-- End #contentInner -->
                            
                            <div class="contentBottomLeft"><div class="contentBottomRight">
                                <div class="contentTopInner"></div>
                            </div></div>
                            
                    </div><!-- End #content -->
                
                </div><!-- End #wrapperContentInner -->
                
            </div>
        </div><!-- End #wrapperInner -->
    </div><!-- End #wrapper -->

<jsp:include page="../../footer.jsp"/>
</body>
</html>
