<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
  <xsl:template name="public_dev_left">
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top">      
                <TR>
                    <TD WIDTH="25" BGCOLOR="#999999" VALIGN="top" ALIGN="right"><IMG SRC="/i/sub_navbox_top_left.gif" WIDTH="25" HEIGHT="1" BORDER="0"/><BR/><IMG SRC="/i/sub_navbox_btm_left.gif" WIDTH="25" HEIGHT="21" BORDER="0"/></TD>
          <TD WIDTH="100%" VALIGN="top" CLASS="moduleTitle" BGCOLOR="#999999">
                  <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top">      
                            <TR><TD COLSPAN="2" WIDTH="140" VALIGN="top" BGCOLOR="#CCCCCC"><IMG SRC="/i/clear.gif" WIDTH="140" HEIGHT="1" BORDER="0"/></TD></TR>                                
                            <TR><TD WIDTH="100%" VALIGN="middle" CLASS="statTextBig" BGCOLOR="#333333">&#160;:: Projects </TD><TD WIDTH="5" BGCOLOR="#333333" ALIGN="right"><IMG SRC="/i/sub_nav_title_right.gif" WIDTH="5" HEIGHT="21" BORDER="0"/></TD></TR>
                        </TABLE>                    
                    </TD>
                </TR>
      </TABLE>
      <TABLE WIDTH="100%" BORDER="0" CELLSPACING="0" CELLPADDING="0" VALIGN="top" BACKGROUND="/i/steel_gray_bg2.gif" BGCOLOR="#43515E"> 
        <TR><TD COLSPAN="2" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0" VSPACE="2"/></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>                     
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=architect" CLASS="subNav">Architect</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=dde2" CLASS="subNav">Distributed Development Environment</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>                    
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=gcc" CLASS="subNav">GCC Upgrade Analysis</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=grant_process" CLASS="subNav">Grant Processing Application</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=calendar_comp" CLASS="subNav">Calendar Component</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>    
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=pdf_cci" CLASS="subNav">PDF Conversion Component Implementation Project</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=editorial" CLASS="subNav">Website Editorial</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=dde1" CLASS="subNav">Design of the TopCoder Distributed Development Environment</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=tces1" CLASS="subNav">TCES Extension Part One</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=admin_cmd" CLASS="subNav">Admin Commands</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=chat" CLASS="subNav">Moderated Chat Session</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=team" CLASS="subNav">Teams</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=notify" CLASS="subNav">Notification Component</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=pdf_conversion" CLASS="subNav">PDF Conversion Design</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=calendar" CLASS="subNav">Calendar Component</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=file_upload" CLASS="subNav">File Upload Component</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=web_services_proto" CLASS="subNav">Web Services Proof of Concept</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=client_impl" CLASS="subNav">Client and Communication Protocol Implementation</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=email" CLASS="subNav">Email</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=payment" CLASS="subNav">Payment Affidavit Contract Tracking</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=client" CLASS="subNav">Client and Communication Protocol Design</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR> 
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=tracking" CLASS="subNav">Request Tracking System</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=project" CLASS="subNav">Project Tracking System</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=statistics" CLASS="subNav">Statistics</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
          <TR><TD VALIGN="top" BACKGROUND="" CLASS="subNav" ALIGN="right">&#160;&#160;::&#160;&#160;</TD><TD VALIGN="top" HEIGHT="15" BACKGROUND="" CLASS="subNav" WIDTH="100%"><A HREF="/index?t=development&amp;c=c" CLASS="subNav">C# System Design Project</A></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD COLSPAN="2" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0" VSPACE="2"/></TD><TD WIDTH="1" BACKGROUND=""><IMG SRC="/i/clear.gif" WIDTH="1" HEIGHT="1" BORDER="0"/></TD></TR>
                <TR><TD COLSPAN="3" BACKGROUND="/i/steel_gray_bg.gif" ALIGN="right"><IMG SRC="/i/sub_navbox_btm_right.gif" WIDTH="13" HEIGHT="17" BORDER="0"/></TD></TR>
      </TABLE>
            <IMG SRC="/i/logo_ghosted_bracket.gif" WIDTH="160" HEIGHT="77" BORDER="0" ALT="[ TopCoder ]" VSPACE="10"/>
  </xsl:template>
</xsl:stylesheet>                     
